// The smoke test: `npm test`. Boots the real game (game/index.html) in a hidden Electron window and
// plays one day through the test handle: a truck docks, pallets are unloaded by hand and by jack,
// stock goes on the racks, an order is picked, packed, loaded and dispatched, staff work a shift,
// the forklift stores a pallet on the shelf level, and the save survives a reload. Any page error fails it.
'use strict';
const { app, BrowserWindow } = require('electron');
const path = require('path');
const fs = require('fs');
const os = require('os');

process.env.ELECTRON_DISABLE_SECURITY_WARNINGS = 'true';   // the dev-mode CSP notice is not a game error
app.setPath('userData', fs.mkdtempSync(path.join(os.tmpdir(), 'depotco-test-')));   // never the player's saves
app.commandLine.appendSwitch('enable-unsafe-swiftshader');
if (process.env.CI) app.disableHardwareAcceleration();

const SCENARIO = `(async () => {
  const out = [], errs = [];
  const ok = (cond, msg) => { out.push((cond ? 'ok   ' : 'FAIL ') + msg); if (!cond) errs.push(msg); };
  try {
  const T = window.DEPOT.T, S = T.S;
  let mkN = 0; const mkOrder = () => { let o = T.genOrder(false); if (!o) { S.orders = S.orders.filter((x) => x.state !== 'open'); const sk = ['cereal', 'lamps', 'bolts', 'paint'][mkN % 4]; S.slots[T.slotKey(2, 9 + (mkN % 4), 0)] = { sku: sk, n: 12, pal: true }; mkN++; o = T.genOrder(false); } if (!o) throw new Error('mkOrder: no order even with fresh stock'); return o; };
  const quietDocks = () => { [0, 1, 2].forEach((d) => [0, 1].forEach((w) => { S.flags['out' + S.day + '-' + d + '-' + w] = 1; })); };   // no scheduled outbound truck docks while a test has its own truck at a door   // the deck accounts can claim every free box: a test order brings its own stock when it must
  window.DEPOT.enter();
  ok(S.day === 1 && S.bank === 600, 'fresh save: day 1, $600');
  // the first truck
  T.setTime(7.2); T.run(30);
  const tin = T.truckAtDoor(0);
  ok(!!tin, 'inbound truck docked at IN 1');
  ok(tin && tin.pallets.length >= 2, 'truck carries pallets: ' + (tin && tin.pallets.length));
  S.flags.noEvents = 1;   // no random power cuts: the long automation runs need the mains
  T.setDoor(0, true); T.run(0.5); ok(!T.doorPassable(0), 'door panel still rising after half a second'); T.run(3); const tdr = T.truckAtDoor(0); if (tdr) { T.run(30); const mdr = T.truckMeshes[tdr.id]; ok(mdr.drvD > 20, 'the driver walked in from the cab: ' + mdr.drvD.toFixed(1) + ' m'); } ok(T.floorY(-30.2, -14) === 0, 'the dock leveller bridges the slot between the floor edge and the bed'); ok(T.doorPanelScale(0) < 0.99, 'and the panel mesh has started to rise'); T.run(2.5); ok(T.doorPassable(0), 'door panel up after three seconds');
  ok(S.doors[0] === true, 'door IN 1 open');
  ok(/Sign the delivery note/.test(T.palletPrompt({ kind: 'pallet', id: tin.pallets[0] })), 'pallets wait for the signature: ' + T.palletPrompt({ kind: 'pallet', id: tin.pallets[0] }));
  T.signTruck(tin); ok(tin.signed === true, 'delivery note signed');
  const p0 = T.palletById(tin.pallets[0]);
  ok(T.palletPrompt({ kind: 'pallet', id: p0.id }) !== null, 'pallet on the truck has a prompt: ' + T.palletPrompt({ kind: 'pallet', id: p0.id }));
  const bank0 = S.bank;
  T.palletUse({ kind: 'pallet', id: p0.id });
  ok(S.hand && S.hand.kind === 'box' && S.hand.sku === p0.sku, 'took a box by hand');
  ok(S.bank === bank0 + 12, 'receiving fee paid once the pallet is touched');
  const k00 = T.slotKey(0, 0, 0);
  T.slotUse(k00);
  ok(!S.hand && S.slots[k00] && S.slots[k00].n === 1, 'box stored in A1 floor');
  // the jack
  T.grabTool('jack'); ok(T.player.tool === 'jack', 'grabbed the jack');
  T.palletUse({ kind: 'pallet', id: p0.id }); ok(S.jack.pallet === p0.id, 'jack lifted the pallet');
  const k01 = T.slotKey(0, 1, 0); const n = p0.n;
  T.slotUse(k01); ok(!S.jack.pallet && S.slots[k01] && S.slots[k01].n === n, 'jack stored the pallet in A2: ' + n + ' boxes');
  T.releaseTool(); ok(T.player.tool === null, 'released the jack');
  // the rest of the load, straight to the racks
  S.pallets.filter((p) => p.place === 'truck').forEach((p) => { const k = T.findSlotFor(p.sku, p.n, 1); ok(!!k, 'slot found for ' + p.sku); if (k) { T.palletUse({ kind: 'pallet', id: p.id }); T.handSet(null); const pl = T.palletById(p.id); if (pl) { pl.place = 'floor'; T.storePallet(pl, k); } } });
  T.run(30);
  ok(!T.truckAtDoor(0), 'emptied truck left the dock');
  ok(T.totalStock() > 0, 'stock on the racks: ' + T.totalStock());
  // an order, picked and packed the real way
  T.setTime(9); const o = T.genOrder(false); ok(!!o, 'order generated #' + (o && o.num));
  o.lines.forEach((l) => { while (T.stockCount(l.sku) < l.qty) { const k = T.findSlotFor(l.sku, 1, 1); S.slots[k] = S.slots[k] && S.slots[k].n ? S.slots[k] : { sku: l.sku, n: 0 }; S.slots[k].n += 1; } });
  const firstLine = o.lines[0]; const srcKey = Object.keys(S.slots).find((k) => S.slots[k].sku === firstLine.sku && S.slots[k].n > 0);
  T.player.x = 25.5; T.player.z = 5.2;
  T.slotUse(srcKey); ok(S.hand && S.hand.sku === firstLine.sku, 'picked one box for the order');
  T.benchUse(); ok(!S.hand && S.bench.boxes[firstLine.sku] === 1, 'box on the bench');
  o.lines.forEach((l, i) => { const need = l.qty - (i === 0 ? 1 : 0); for (let q = 0; q < need; q++) { const k = Object.keys(S.slots).find((kk) => S.slots[kk].sku === l.sku && S.slots[kk].n > 0); S.slots[k].n--; if (!S.slots[k].n) delete S.slots[k]; T.benchAdd(l.sku, 1); } });
  ok(T.canPack(o), 'order packable from the bench');
  ok(T.packOrder(o) && o.state === 'packing', 'order released to the pack line'); T.run(30); if (S.pack.jam) { T.packUse(); T.run(15); } ok(o.state === 'packed' && S.bench.parcels[0] === o.id, 'pack line made the parcel: on the shelf ' + JSON.stringify({ st: o.state, pack: S.pack, pi: T.beltItems('packIn').length, po: T.beltItems('packOut').length, inst: !!T.propInst.packline, sink: T.beltSink(T.BELTS.packIn) ? (T.beltSink(T.BELTS.packIn).machine || T.beltSink(T.BELTS.packIn).belt).id : null, power: S.events.power }));
  // ship it
  T.setTime(10.3); T.run(30);
  const tout = T.truckAtDoor(2); ok(!!tout, 'outbound truck docked at OUT 1');
  T.setDoor(2, true);
  T.shelfUse({ kind: 'shelf', order: o.id }); ok(S.hand && S.hand.kind === 'parcel', 'parcel in hand');
  T.loadUse(tout.id); ok(!S.hand && tout.parcels.length === 1 && o.state === 'loaded', 'parcel loaded');
  ok(/Dispatch/.test(T.consolePrompt(2)), 'console offers dispatch: ' + T.consolePrompt(2));
  const bank1 = S.bank; T.consoleUse(2);
  ok(tout.state === 'leaving', 'truck leaving');
  ok(S.bank > bank1 && S.shipped[0] && S.shipped[0].num === o.num, 'paid ' + (S.bank - bank1) + ' for order #' + o.num);
  T.run(15); ok(!S.trucks.some((t) => t.id === tout.id), 'outbound truck gone');
  // the office PC and the shop
  T.openPanel('pc', 'shop'); ok(/Picking cart/.test(T.panelHtml()), 'shop renders'); T.closePanel();
  S.bank += 5000; S.level = 3; T.buyUpgrade('cart'); ok(S.up.cart === true, 'bought the cart');
  T.buyUpgrade('fork'); ok(S.up.fork === true, 'bought the forklift');
  T.buyUpgrade('row3'); ok(S.up.rows === 3, 'bought the third row');
  // tiers: each needs the one before; the stacker reaches the second level; the tune-up opens the 250 and 300% dial steps
  { S.bank += 20000; const lvl0 = S.level; S.level = Math.max(S.level, 6); T.buyUpgrade('jackLift'); ok(!S.up.jackLift, 'the stacker needs the powered truck first'); T.buyUpgrade('jackPower'); T.buyUpgrade('jackLift'); ok(!!S.up.jackPower && !!S.up.jackLift, 'bought the powered truck, then the stacker');
    const lk = T.slotKey(0, 10, 1); delete S.slots[lk]; const lp = T.newPallet('toys', 3, { place: 'jack' }); S.jack.pallet = lp.id; T.player.tool = 'jack'; T.slotUse(lk); ok(!S.jack.pallet && !!S.slots[lk] && S.slots[lk].n === 3, 'the stacker set a pallet on the second level: ' + JSON.stringify(S.slots[lk] || null)); T.player.tool = null; delete S.slots[lk];
    T.buyUpgrade('plantTune'); S.speed = {}; for (let k = 0; k < 4; k++) T.speedCycle('packline'); ok(!!S.up.plantTune && T.speedOf('packline') === 3, 'the tune-up opens the 300% step: dial now ' + T.speedOf('packline')); S.speed = {};
    T.buyUpgrade('agvFast'); ok(!!S.up.agvFast === !!S.up.agv, 'AGV fast drive needs the AGV: agv=' + !!S.up.agv + ' fast=' + !!S.up.agvFast); S.level = lvl0; }
  // staff: a second truck, the receiver puts it away, the picker feeds the bench
  T.hireStaff('receiver'); T.hireStaff('picker'); ok(S.staff.length === 2, 'two staff hired');
  S.staff.forEach((st) => { st.arriveOff = 0; st.sick = false; st.dayOff = false; }); T.setTime(12.9); T.run(60);
  ok(S.staff.every((st) => st.clocked), 'both clocked in at the reader: ' + S.staff.map((st) => T.staffStatus(st)).join(' / '));
  T.setTime(13.3); T.run(30); const t2 = T.truckAtDoor(0); ok(!!t2, 'second inbound truck docked');
  T.setDoor(0, true); T.signTruck(t2);
  const putaway0 = S.stats.putaway; T.run(150);
  ok(S.staff[0].hoursToday > 0.5, 'hours accrue on the clock: ' + S.staff[0].hoursToday.toFixed(2));
  T.myClock(true); ok(S.clockedIn === true, 'you clocked in'); T.myClock(false); ok(S.clockedIn === false && S.stats.hoursWorked >= 0, 'you clocked out with a shift report');
  ok(S.stats.putaway > putaway0, 'receiver put pallets away: ' + (S.stats.putaway - putaway0) + ' boxes');
  // the morning after a clock-out: the leaving flag from last night must not keep a clocked-in worker idle at the clock
  { const pk = S.staff.filter((st) => st.role === 'picker')[0]; const t0 = S.time; pk.leaving = true; pk.leavingWait = false; pk.state = 'idle'; pk.clocked = true; pk.task = null; pk.carry = null; pk.after = null; T.setTime(10); T.run(3); ok(pk.state !== 'idle' || !!pk.task, 'a worker who clocked out last night works again today: state=' + pk.state + ' task=' + JSON.stringify(pk.task)); pk.leaving = false; T.setTime(t0); }
  const o2 = T.genOrder(false); ok(!!o2, 'second order #' + (o2 && o2.num));
  o2.lines.forEach((l) => { while (T.stockCount(l.sku) < l.qty) { const k = T.findSlotFor(l.sku, 1, 1); S.slots[k] = S.slots[k] && S.slots[k].n ? S.slots[k] : { sku: l.sku, n: 0 }; S.slots[k].n += 1; } });
  T.run(120); ok(Object.keys(S.bench.boxes).length > 0, 'picker brought boxes to the bench: ' + JSON.stringify(S.bench.boxes));
  // the forklift: lift a floor pallet and store it on the shelf level
  const fp = T.newPallet('paint', 8, { place: 'floor', x: 3.5, y: 0, z: 19.5, rot: 0 });
  S.fork.x = 2; S.fork.z = 19.5; S.fork.yaw = Math.PI / 2; S.fork.lift = 0.1;
  T.startDrive(); ok(T.ui && window.DEPOT.T.player, 'driving the forklift'); T.forkGearCycle(); T.forkGearCycle(); ok(S.fork.gear === 3, 'Shift cycled to gear 3'); T.forkGearCycle(); ok(S.fork.gear === 1, 'and back round to gear 1');
  T.forkUse(); ok(S.fork.pallet === fp.id, 'forks lifted the pallet');
  // nose up to the wrapper with the load, then back out: the obstacle you are already inside must not trap you
  const WP = T.propInst.wrapper.P; S.fork.x = WP.x; S.fork.z = WP.z + 1.6; S.fork.yaw = Math.PI; T.player.x = WP.x; T.player.z = WP.z + 2.8; T.startDrive(); T.player.keys.KeyS = true; T.run(1.5); T.player.keys.KeyS = false; T.stopDrive(); ok(S.fork.z > WP.z + 2.2, 'forklift backed out of the wrapper apron: z ' + S.fork.z.toFixed(2) + ' from ' + (WP.z + 1.6).toFixed(2));
  S.fork.x = -22.5; S.fork.z = T.RACK.rows[1] - 1.6; S.fork.yaw = 0; S.fork.lift = 1.55;
  const k10 = T.slotKey(1, 0, 1); delete S.slots[k10];
  T.forkUse(); ok(!S.fork.pallet && S.slots[k10] && S.slots[k10].n === 8, 'pallet stored on B1 shelf by forklift');
  T.stopDrive(); ok(!S.fork.pallet, 'got off the forklift');
  S.fork.x = 0; S.fork.z = 20.5; S.fork.batt = 0.4; T.player.x = 0; T.player.z = 22; T.cableUse('fork'); ok(T.player.tool === 'cable', 'took the charging cable'); T.cablePlugInto('fork'); ok(S.fork.plugged === true && T.player.tool === null, 'forklift plugged in'); const bt0 = S.fork.batt; T.run(20); ok(S.fork.batt > bt0, 'charging while plugged: ' + S.fork.batt.toFixed(2)); T.startDrive(); ok(S.fork.plugged === false, 'driving off pulled the plug'); T.stopDrive();
  // contracts, the bank, damaged goods
  S.level = 3; S.contract = null; S.nextOffer = S.day; T.setTime(9.05); T.run(2); ok(!!S.contract && !S.contract.accepted, 'contract offered');
  S.contract.accepted = true; S.contract.need = 1; const co = T.genOrder(false); co.client = S.contract.client; co.lines = [{ sku: 'bolts', qty: 1 }]; T.benchAdd('bolts', 1); T.packOrder(co); T.run(30); if (S.pack.jam) { T.packUse(); T.run(15); } ok(co.state === 'packed', 'contract order packed by the line');
  delete S.flags['out' + S.day + '-0-0']; S.trucks.filter((t) => t.dir === 'out').forEach((t) => { T.truckLeave(t, 'test'); }); T.run(20); T.setTime(10.4); T.run(30); const tc = T.truckAtDoor(2); ok(!!tc, 'outbound truck for the contract test'); T.setDoor(2, true); T.shelfUse({ kind: 'shelf', order: co.id }); T.loadUse(tc.id); const bankC = S.bank; T.consoleUse(2); ok(S.contract === null && S.bank > bankC, 'the contract counted the on-time ship and paid out the moment its count was met');
  S.staff.forEach((st) => { st.hoursToday = 8; }); S.loan = 5000; const b3 = S.bank; T.setTime(23.9); T.run(16); ok(S.day >= 2 && S.bank < b3 - 5000 * 0.015 + 1, 'loan interest charged at the day roll');
  ok(S.staff[0].sheet && S.staff[0].sheet[0] && S.staff[0].sheet[0].h === 8 && S.staff[0].sheet[0].pay === Math.round(T.hourly(S.staff[0]) * 8), 'wages paid from the timesheet: ' + JSON.stringify(S.staff[0].sheet[0]));
  S.level = 3; T.editToggle(); const rackP = T.propInst.rack0; ok(!!rackP, 'rack row A is a prop'); const sp = T.slotKey(0, 0, 0); if (!S.slots[sp] || !S.slots[sp].n) S.slots[sp] = { sku: 'bolts', n: 2 }; T.editGrab('rack0'); rackP.g.position.set(0.5, 0, -15); T.editDrop(false); ok(Math.abs(T.propInst.rack0.P.x - 0.5) < 0.01 && S.slots[sp] && S.slots[sp].n > 0, 'rack moved with its stock'); T.editReset('rack0'); T.editToggle();
  // the production wing: a pallet of granulate on the jack tips into the hopper, the moulder fills the belt, the palletiser drops a pallet
  ok(T.inWing(-4, -36) && !T.inWing(-4, -20) && T.floorY(-4, -36) === 0, 'the wing is inside');
  ok(T.beltSink(T.BELTS.moulderOut) && T.beltSink(T.BELTS.moulderOut).belt && T.beltSink(T.BELTS.moulderOut).belt.id === 'beltMain' && T.beltSink(T.BELTS.beltMain) && T.beltSink(T.BELTS.beltMain).machine && T.beltSink(T.BELTS.beltMain).machine.id === 'palletiser', 'moulder belt joins the main belt which ends at the palletiser');
  const rawP = T.newPallet('raw', 8, { place: 'jack' }); S.jack.pallet = rawP.id; T.player.tool = 'jack'; T.hopperUse(); ok(S.factory.raw === 40 && !S.jack.pallet, 'granulate tipped into the hopper: 40 units'); T.releaseTool();
  S.factory.product = 'dcbin'; T.moulderUse(); ok(S.factory.on, 'moulding line started'); T.run(20); ok(S.factory.made >= 1 && (T.beltItems('moulderOut').length + T.beltItems('beltMain').length) >= 1, 'a box came off the moulder onto the belt');
  T.run(140); if (S.factory.jam) { T.moulderUse(); T.run(80); } ok(S.pallets.some((p) => p.sku === 'dcbin' && p.place === 'floor' && p.n === 8), 'palletiser dropped a pallet of eight own-brand boxes: made ' + S.factory.made + ', hopper ' + S.factory.raw);
  S.factory.on = false;
  const WPP = T.propInst.wrapper.P, wpal = T.newPallet('paint', 4, { place: 'floor', x: WPP.x, z: WPP.z, y: 0, rot: 0 }); T.player.tool = null; T.player.x = WPP.x; T.player.z = WPP.z + 2.2; S.wrap.film = 5; T.wrapperUse(); T.run(6); ok(wpal.wrapped, 'a pallet set on the turntable gets wrapped');
  const sdP = T.newPallet('cereal', 3, { place: 'jack' }); S.jack.pallet = sdP.id; T.player.tool = 'jack'; T.player.x = -5; T.player.z = 0; T.lookAt(-5, 5, 0.01); T.useFocus(); ok(!S.jack.pallet && sdP.place === 'floor' && Math.abs(sdP.x - (-5)) < 2.5, 'E on open floor sets the jack pallet down'); T.releaseTool();
  // an emptied pallet stays empty; the jack takes it to the empties stack; a slot emptied of its pallet's boxes keeps the empty pallet
  const emP = T.newPallet('soap', 1, { place: 'floor', x: -8, z: -8, y: 0, rot: 0 }); T.player.tool = null; T.handSet(null); T.player.x = -8; T.player.z = -6.5; T.palletUse({ kind: 'pallet', id: emP.id }); ok(T.palletById(emP.id) && emP.n === 0 && !!S.hand, 'the last box off a pallet leaves an empty pallet'); T.handSet(null);
  T.player.tool = 'jack'; T.palletUse({ kind: 'pallet', id: emP.id }); ok(S.jack.pallet === emP.id, 'the jack lifts the empty pallet'); const EP = T.propInst.empties.P; T.player.x = EP.x + 2.0; T.player.z = EP.z; T.lookAt(EP.x, 0.8, EP.z); T.useFocus(); ok(!S.jack.pallet && !T.palletById(emP.id) && S.emptiesN === 1, 'the empties stack took it');
  // pulling a pallet out of a rack takes the wooden pallet with it: no empty pallet stays behind to be pulled again and again
  { const pk3 = T.slotKey(0, 9, 0); S.slots[pk3] = { sku: 'paint', n: 5, pal: true }; T.player.tool = 'jack'; S.jack.pallet = null; T.slotUse(pk3); const jp3 = S.jack.pallet ? T.palletById(S.jack.pallet) : null; ok(!!jp3 && jp3.n === 5 && !S.slots[pk3], 'pulling a pallet of five empties the slot entirely: slot=' + JSON.stringify(S.slots[pk3] || null) + ' onJack=' + (jp3 ? jp3.n : 'none')); if (jp3) { S.pallets.splice(S.pallets.indexOf(jp3), 1); S.jack.pallet = null; } T.player.tool = null; }
  const ek = T.slotKey(0, 3, 0); const sp2 = T.newPallet('toys', 1, { place: 'jack' }); S.jack.pallet = sp2.id; ok(T.storePallet(sp2, ek) && S.slots[ek].pal, 'a stored pallet marks its slot'); S.jack.pallet = null; T.player.tool = null; T.slotUse(ek); T.handSet(null); ok(S.slots[ek] && S.slots[ek].n === 0 && S.slots[ek].pal, 'the slot keeps the empty pallet after the last box'); T.player.tool = 'jack'; T.slotUse(ek); ok(!S.slots[ek] && S.jack.pallet && T.palletById(S.jack.pallet).n === 0, 'the jack pulls the empty pallet out of the slot'); T.releaseTool();
  // automation: the shipping belt feeds the dock loader, the AGV puts a pallet away
  S.up.shipbelt = true; T.buildProp('shipBelt'); T.buildProp('dockLoader2'); T.buildProp('bay2'); S.up.agv = true; T.buildProp('agvDock'); S.events.power = false;
  ok(T.beltSink(T.BELTS.shipBelt) && T.beltSink(T.BELTS.shipBelt).machine && T.beltSink(T.BELTS.shipBelt).machine.id === 'bay2' && !!T.propInst.bay2, 'the shipping belt ends in the OUT 2 shipping bay, which stands beside the loader');
  S.trucks.filter((t) => t.dir === 'out').forEach((t) => T.truckLeave(t, 'test')); T.run(20); const dl = T.spawnTruck('out', 1, 18); dl.x = T.HALL.x + 0.4; T.run(3); ok(dl.state === 'docked' && T.truckAtDoor(3) === dl, 'an outbound truck is at OUT 2 for the loader'); T.setDoor(3, true); T.run(4);
  const ao = T.genOrder(false); ao.lines = [{ sku: 'bolts', qty: 1 }]; T.benchAdd('bolts', 1); T.packOrder(ao); T.run(40); if (S.pack.jam) { T.packUse(); T.run(20); } T.run(90); ok(ao.state === 'loaded' || ao.state === 'shipped', 'the parcel rode the belt and the dock loader put it on the truck: ' + ao.state);
  const agvP = T.newPallet('cereal', 4, { place: 'floor', x: T.wallX(-26.5, -2.9, false), z: -2.9, y: 0, rot: 0 }); const put0 = S.stats.agvPutaway || 0; T.run(60); for (let w = 0; w < 8 && T.palletById(agvP.id); w++) T.run(30); ok((S.stats.agvPutaway || 0) >= put0 + 1 && !T.palletById(agvP.id), 'the AGV put the pallet away: ' + JSON.stringify({ state: T.agvState().state, put: S.stats.agvPutaway, pal: T.palletById(agvP.id) && T.palletById(agvP.id).place, agv: [+T.agvState().x.toFixed(1), +T.agvState().z.toFixed(1)], target: T.agvState().target, path: (T.agvState().path || []).slice(0, 6).map((q) => [+q.x.toFixed(1), +q.z.toFixed(1)]), key: T.agvState().key }));
  // the gantry picks a box the bench needs out of row A and the pick belt lands it on the bench
  S.up.gantry = true; S.flags.noOrders = 1; T.buildGantries(); ok(!!T.propInst.gantry0 && !!T.propInst.gantry1 && !T.propInst.gantry4, 'a crane stands over every owned row (rows: ' + S.up.rows + ')'); ok(T.beltSink(T.BELTS.pickBelt) && T.beltSink(T.BELTS.pickBelt).belt && T.beltSink(T.BELTS.pickBelt).belt.id === 'pickMerge', 'the south pick belt hands over to the merge belt'); ok(T.beltSink(T.BELTS.pickMerge) && T.beltSink(T.BELTS.pickMerge).machine && T.beltSink(T.BELTS.pickMerge).machine.id === 'benchIn', 'the merge belt ends at the bench');
  const gk = T.slotKey(0, 2, 0); for (const k in S.slots) if (S.slots[k] && S.slots[k].sku === 'soap') delete S.slots[k]; S.pallets.forEach((p) => { if (p.sku === 'soap') p.sku = 'bolts'; }); S.staff.forEach((st) => { if (st.carry && st.carry.sku === 'soap') st.carry = null; }); S.slots[gk] = { sku: 'soap', n: 3, pal: true }; S.bench.boxes = {}; const go2 = T.genOrder(false); go2.lines = [{ sku: 'soap', qty: 1 }]; S.orders = S.orders.filter((o) => o === go2 || o.state !== 'open'); T.beltItems('pickBelt').length = 0; T.gantryState(0).state = 'idle'; T.gantryState(0).sku = null; T.gantryState(1).state = 'idle'; T.gantryState(1).sku = null; const b0g = S.bench.boxes.soap || 0; T.run(110); ok((S.bench.boxes.soap || 0) >= b0g + 1 && S.slots[gk].n === 2, 'the gantry picked a soap box out of A3 and the belt put it on the bench: gantry ' + JSON.stringify({ st: T.gantryState(0).state, x: +T.gantryState(0).x.toFixed(2), lift: +T.gantryState(0).lift.toFixed(2), sku: T.gantryState(0).sku, belt: T.beltItems('pickBelt').length, slot: S.slots[gk] && S.slots[gk].n }));
  const gk2 = T.slotKey(1, 7, 0); for (const k in S.slots) if (S.slots[k] && S.slots[k].sku === 'coffee') delete S.slots[k]; S.pallets.forEach((p) => { if (p.sku === 'coffee') p.sku = 'bolts'; }); S.slots[gk2] = { sku: 'coffee', n: 2, pal: true }; const go3 = T.genOrder(false); go3.lines = [{ sku: 'coffee', qty: 1 }]; S.orders = S.orders.filter((o) => o === go3 || o.state !== 'open'); S.bench.boxes = {}; T.beltItems('pickBelt').length = 0; T.gantryState(0).state = 'idle'; T.gantryState(0).sku = null; T.gantryState(1).state = 'idle'; T.gantryState(1).sku = null; T.run(60); ok(S.slots[gk2].n === 1 && (T.gantryState(1).sku === 'coffee' || T.beltItems('pickBelt').some((it) => it.sku === 'coffee') || (S.bench.boxes.coffee || 0) > 0 || T.beltItems('pickMerge').some((it) => it.sku === 'coffee') || S.floor.some((f) => f.kind === 'box' && f.sku === 'coffee') || go3.state !== 'open' || S.staff.some((st) => st.carry && st.carry.sku === 'coffee')), 'the gantry picked a coffee box out of row B (B8), now downstream or packed: ' + JSON.stringify({ st: T.gantryState(1).state, x: +T.gantryState(1).x.toFixed(2), slot: S.slots[gk2].n, merge: T.beltItems('pickMerge').length, belt: T.beltItems('pickBelt').length, bench: S.bench.boxes, order: go3.state, floor: S.floor.filter((f) => f.kind === 'box').length }));
  // the mezzanine (1.14.0): buy it; the deck is 4.6 m up only for someone already up there; a pallet set in the lift goes up, rolls down the feed belt and is racked upstairs; an order for it is picked by the upper crane and comes down the chute into the pick line
  { S.bank += 20000; const lv = S.level; S.level = Math.max(S.level, 6); S.events.power = false; S.flags.noOrders = 1; T.buyUpgrade('upper'); ok(!!S.up.upper && !!T.propInst.mezz && !!T.propInst.lift && !!T.propInst.rack5 && !!T.propInst.gantry5 && !!T.propInst.upperFeed && !!T.propInst.upperPick, 'bought the mezzanine: deck, lift, upper row, crane and both belts stand');
    ok(T.floorYAt(-30, -18, 0) === 0 && T.floorYAt(-30, -18, 4.6) === 4.6 && Math.abs(T.floorYAt(-20.8, -22.6, 0) - 2.3) < 0.1 && T.floorYAt(-18, -22.6, 4.6) === 4.6 && T.floorYAt(-31.0, -15.5, 4.6) === 0, 'the deck counts only for someone up there, the stair rises along the north wall, the shaft is open');
    ok(T.beltSink(T.BELTS.upperFeed) && T.beltSink(T.BELTS.upperFeed).machine && T.beltSink(T.BELTS.upperFeed).machine.id === 'upperIn' && T.beltSink(T.BELTS.upperPick) && T.beltSink(T.BELTS.upperPick).belt && T.beltSink(T.BELTS.upperPick).belt.id === 'upperChute' && T.beltSink(T.BELTS.upperChute) && T.beltSink(T.BELTS.upperChute).belt && T.beltSink(T.BELTS.upperChute).belt.id === 'pickBelt', 'the feed belt ends at the upper intake, the pick belt at the chute, the chute in the south pick belt');
    const up = T.newPallet('coffee', 6, { place: 'jack' }); S.jack.pallet = up.id; T.player.tool = 'jack'; T.player.x = -28.4; T.player.z = -15.5; T.player.y = 0; T.lookAt(-31.0, 1.0, -15.5); T.useFocus(); ok(up.place === 'lift' && !S.jack.pallet && T.liftState().pallet === up.id, 'E with the loaded jack set the pallet in the lift: ' + up.place + ' / ' + T.focusText()); T.player.tool = null;
    T.run(32); const upKeys = Object.keys(S.slots).filter((k) => k.split(',')[0] === '5' && S.slots[k].n > 0); ok(T.liftState().state === 'down' && !T.liftState().pallet && upKeys.length === 1 && S.slots[upKeys[0]].sku === 'coffee' && S.slots[upKeys[0]].n === 6, 'the lift went up, the pallet rolled down the feed belt and is racked upstairs: ' + JSON.stringify({ lift: T.liftState().state, slots: upKeys, feed: T.beltItems('upperFeed').length }));
    for (const k in S.slots) if (S.slots[k] && S.slots[k].sku === 'coffee' && k.split(',')[0] !== '5') delete S.slots[k]; S.pallets.forEach((p) => { if (p.sku === 'coffee') p.sku = 'bolts'; }); S.staff.forEach((st) => { if (st.carry && st.carry.sku === 'coffee') st.carry = null; st.task = null; }); S.bench.boxes = {}; ['pickBelt', 'pickBelt2', 'pickMerge', 'upperPick'].forEach((b) => { T.beltItems(b).length = 0; }); S.floor = S.floor.filter((f) => !(f.kind === 'box' && f.sku === 'coffee')); T.gantryState(5).state = 'idle'; T.gantryState(5).sku = null;
    const uo = T.genOrder(false); uo.lines = [{ sku: 'coffee', qty: 1 }]; S.orders = S.orders.filter((o) => o === uo || o.state !== 'open'); T.run(160); const downstream = (S.bench.boxes.coffee || 0) + ['pickBelt', 'pickMerge', 'upperPick'].reduce((a, b) => a + T.beltItems(b).filter((it) => it.sku === 'coffee').length, 0) + (uo.state !== 'open' ? 1 : 0); const upSlot = upKeys.length ? S.slots[upKeys[0]] : null;
    ok(upSlot && upSlot.n === 5 && downstream >= 1, 'the upper crane picked a coffee box for the order and it came down the chute into the pick line: ' + JSON.stringify({ upSlot: upSlot ? upSlot.n : null, crane: T.gantryState(5).state, bench: S.bench.boxes.coffee || 0, order: uo.state, belts: ['upperPick', 'pickBelt', 'pickMerge'].map((b) => b + ':' + T.beltItems(b).length).join(' ') }));
    S.orders = S.orders.filter((o) => o !== uo); S.flags.noOrders = 0; S.level = lv; }
  // the lanes (1.14.0): every order carries its client's lane; it is due at its own dock's next truck; a parcel out of the wrong door pays the fee
  { S.flags.noOrders = 1; T.setTime(15.0); quietDocks(); const lo = mkOrder();   /* a quiet hour: no sea or land truck window opens while the test has its own truck at the door */ ok(!!lo && !!T.MODES[lo.mode] && lo.mode === T.orderMode(lo) && lo.mode !== 'air', 'an order carries its lane (' + (lo && lo.mode) + ') and air waits for the deck');
    const wrongDoor = lo.mode === 'sea' ? 3 : 2; S.trucks.filter((t) => t.dir === 'out').forEach((t) => T.truckLeave(t, 'test')); T.run(20); const wt = T.spawnTruck('out', wrongDoor - 2, 23); wt.x = T.HALL.x + 0.4; T.run(3); T.setDoor(wrongDoor, true); T.run(4);
    lo.state = 'packed'; S.bench.parcels.push(lo.id); S.hand = null; T.handSet(null); T.shelfUse({ kind: 'shelf', order: lo.id }); T.loadUse(wt.id); ok(wt.parcels.indexOf(lo.id) >= 0, 'the parcel went into the truck of the wrong lane anyway');
    const payBefore = S.bank, mis0 = S.stats.misrouted || 0, dbg0 = JSON.stringify({ wt: wt.state, parcels: wt.parcels.length, lo: lo.state, time: +S.time.toFixed(2), door: wrongDoor, at: !!T.truckAtDoor(wrongDoor) }); T.consoleUse(wrongDoor); const paid = S.bank - payBefore; ok(paid === Math.round(lo.pay * 0.75) && (S.stats.misrouted || 0) === mis0 + 1, 'paid ' + paid + ' of ' + lo.pay + ': the forwarding fee for the wrong door, counted as misrouted ' + dbg0 + ' after: ' + JSON.stringify({ wt: wt.state, lo: lo.state, mis: S.stats.misrouted })); T.run(15); S.flags.noOrders = 0; }
  // the sortation deck: OUT 3 opens, the loaders and the deck stand, every belt hands over to the next, a parcel of each lane rides the spiral up, gets its form in its cell and comes down into the truck of its lane
  { S.bank += 30000; const lv2 = S.level, tm0 = S.time; S.level = Math.max(S.level, 6); S.events.power = false; S.flags.noOrders = 1; S.flags.noEvents = 1;
    ok(!T.setDoor(4, true) && S.doors[4] === false, 'OUT 3 stays shut before the deck is bought'); T.buyUpgrade('sorter');
    ok(!!S.up.sorter && !!T.propInst.sortUp && !!T.propInst.spine && !!T.propInst.collector && !!T.propInst.spiralSea && !!T.propInst.spiralAir && !!T.propInst.cellsea && !!T.propInst.cellland && !!T.propInst.cellair && !!T.propInst.sortTable && !!T.propInst.scanner && !!T.propInst.dockLoader1 && !!T.propInst.dockLoader3 && !T.propInst.shipBelt, 'bought the sortation deck: the spiral, the spine, the cells, the collector, the spirals, the two new loaders stand and the shipping belt is gone');
    const sinkOf = (b) => { const sk = T.beltSink(T.BELTS[b]); return sk ? (sk.belt ? 'belt ' + sk.belt.id : sk.machine ? 'mach ' + sk.machine.id : 'slot') : 'none'; };
    ok(sinkOf('sortUp') === 'belt spine' && sinkOf('spine') === 'mach sortTable' && sinkOf('collector') === 'mach bay2' && sinkOf('spiralSea') === 'mach bay1' && sinkOf('spiralAir') === 'mach bay3' && !!T.propInst.bay1 && !!T.propInst.bay3, 'spiral to spine, spine to turntable, collector to the OUT 2 bay, the sea spiral to the OUT 1 bay, the air spiral to the OUT 3 bay: ' + ['sortUp', 'spine', 'collector', 'spiralSea', 'spiralAir'].map((b) => b + '>' + sinkOf(b)).join(' '));
    ok(T.floorYAt(32.2, -19.3, 4.6) !== 4.6 && T.floorYAt(28, -17.0, 4.6) === 4.6, 'the spiral well is a hole in the deck');
    ok(Math.abs(T.SPOT.jack2.x - T.SORT.jack2.x) < 0.01 && Math.abs(S.jack2.x - T.SORT.jack2.x) < 0.01, 'jack 2 moved out from under the spirals to ' + T.SPOT.jack2.x + ',' + T.SPOT.jack2.z);
    quietDocks(); S.trucks.filter((t) => t.dir === 'out').forEach((t) => T.truckLeave(t, 'test')); T.run(20); const trucks = [0, 1, 2].map((d) => { const t = T.spawnTruck('out', d, 23); t.x = T.HALL.x + 0.4; return t; }); T.run(3); [2, 3, 4].forEach((d) => T.setDoor(d, true)); T.run(5);
    ok(trucks.every((t) => t.state === 'docked') && S.doors[4] === true && T.truckAtDoor(4) === trucks[2] && trucks[2].mode === 'air' && trucks[0].mode === 'sea', 'a truck of each lane is docked, OUT 3 open with the air truck at it');
    const byMode = {}; S.bench.parcels.length = 0; ['sea', 'land', 'air'].forEach((m) => { const c = T.S.orders.length; const o = mkOrder(); o.client = ({ sea: 'hardware', land: 'grocer', air: 'sports' })[m]; o.mode = m; o.lines.forEach((l) => { l.packed = l.qty; }); o.due = (S.day + 1) * 24; o.state = 'packed'; S.bench.parcels.push(o.id); byMode[m] = o; });
    T.run(260); const where = (o) => trucks.map((t, i) => t.parcels.indexOf(o.id) >= 0 ? 'truck' + i : null).filter(Boolean)[0] || o.state;
    ok(where(byMode.sea) === 'truck0' && where(byMode.land) === 'truck1' && where(byMode.air) === 'truck2', 'each parcel went up the spiral, through its cell and down into the truck of its lane: ' + JSON.stringify({ sea: where(byMode.sea), land: where(byMode.land), air: where(byMode.air), sort: T.sortState().count, spine: T.beltItems('spine').length, coll: T.beltItems('collector').length, up: T.beltItems('sortUp').length, table: T.sortState().table.length }));
    ok(byMode.sea.form === 'crate' && byMode.land.form === 'strap' && byMode.air.form === 'pouch' && T.sortState().scanned >= 3 && T.sortState().sorted >= 3, 'the cells gave each its form: ' + [byMode.sea.form, byMode.land.form, byMode.air.form].join(' '));
    const payA = S.bank, mis1 = S.stats.misrouted || 0; T.consoleUse(4); ok(S.bank - payA === byMode.air.pay && (S.stats.misrouted || 0) === mis1, 'the air truck paid the air order in full (' + (S.bank - payA) + '), nothing misrouted'); trucks.slice(0, 2).forEach((t) => T.truckLeave(t, 'test')); T.run(15);
    const ao = mkOrder(); ok(!!ao, 'orders keep coming with the deck'); S.orders = S.orders.filter((o) => o !== ao); S.flags.noOrders = 0; S.level = lv2; T.setTime(tm0); }   // the deck run took game hours; the tests after this one expect the afternoon they had
  // staging and the night shift (1.14.0): a loader with no truck stages the parcel; a docked truck empties the stage; the deck sorts what it holds while you sleep
  { S.flags.noOrders = 1; S.bank += 10000; S.events.power = false; const lvN = S.level; S.level = Math.max(S.level, 6); quietDocks(); S.trucks.filter((t) => t.dir === 'out').forEach((t) => T.truckLeave(t, 'test')); T.run(20); for (const k in S.stage) S.stage[k].length = 0;
    const so = mkOrder(); so.client = 'grocer'; so.mode = 'land'; so.due = (S.day + 1) * 24; so.lines.forEach((l) => { l.packed = l.qty; }); so.state = 'packed'; T.beltItems('collector').length = 0; T.beltItems('collector').push({ kind: 'parcel', order: so.id, mode: 'land', form: 'strap', d: 999 }); T.run(2);
    ok(T.stageOf('dockLoader2').indexOf(so.id) >= 0 && so.state === 'packed' && T.parcelExists(so.id) && T.beltItems('collector').length === 0, 'the land spiral dropped the parcel into the OUT 2 shipping bay with no truck in: ' + JSON.stringify({ stage: T.stageOf('dockLoader2').length, coll: T.beltItems('collector').length }));
    const lt = T.spawnTruck('out', 1, 23); lt.x = T.HALL.x + 0.4; T.run(3); T.setDoor(3, true); T.run(6); ok(lt.parcels.indexOf(so.id) >= 0 && so.state === 'loaded' && T.stageOf('dockLoader2').length === 0, 'the land truck that docked took the staged parcel by itself'); T.truckLeave(lt, 'test'); T.run(15);
    T.buyUpgrade('deckNight'); ok(!!S.up.deckNight, 'bought the deck night shift');
    const n1 = mkOrder(), n2 = mkOrder(); n1.client = 'hardware'; n1.mode = 'sea'; n2.client = 'sports'; n2.mode = 'air'; [n1, n2].forEach((o) => { o.due = (S.day + 2) * 24; o.lines.forEach((l) => { l.packed = l.qty; }); o.state = 'packed'; S.bench.parcels.push(o.id); });
    const d0 = S.day; T.setTime(19); T.sleepNow(); T.run(0.2); ok(S.day === d0 + 1 && T.stageOf('dockLoader1').indexOf(n1.id) >= 0 && T.stageOf('dockLoader3').indexOf(n2.id) >= 0 && n1.form === 'crate' && n2.form === 'pouch' && S.bench.parcels.indexOf(n1.id) < 0, 'overnight the deck sorted the shelf: the sea parcel waits crated at OUT 1, the air parcel bagged at OUT 3: ' + JSON.stringify({ day: S.day, s1: T.stageOf('dockLoader1').length, s3: T.stageOf('dockLoader3').length, forms: [n1.form, n2.form] }));
    T.player.tool = null; T.releaseTool(); S.hand = null; T.handSet(null); T.player.x = 34.2; T.player.z = -11.79; T.player.y = 0; const sp = T.lookAt(34.88, 0.78, -11.79); ok(/Take parcel #/.test(sp || ''), 'a parcel in the OUT 1 bay can be taken by hand: ' + sp); if (/Take parcel #/.test(sp || '')) { T.useFocus(); const hf = S.hand && S.hand.kind === 'parcel' ? T.orderById(S.hand.order).form : null; ok(hf === 'crate', 'the crate came out of the bay as a crate and stays one in the hand: ' + hf); T.player.x = 28.0; T.player.z = -9.0; T.putDown(); const fl = S.floor[S.floor.length - 1]; ok(fl && fl.kind === 'parcel' && T.orderById(fl.order).form === 'crate', 'and set down on the floor it is still a crate'); S.floor.pop(); }
    [so, n1, n2].forEach((o) => { S.orders = S.orders.filter((x) => x !== o); }); for (const k in S.stage) S.stage[k].length = 0; S.flags.noOrders = 0; S.level = lvN; }
  // the deck accounts, the staff options, the plant page, the console that signs the note
  { ok(T.activeClients().filter((c) => c.deck).length === 3 && T.activeClients().length === 9, 'three deck accounts order once the deck stands');
    const w = S.staff[0]; S.bank += 5000; w.trained = false; w.raise = false; w.shift = 'day'; w.cross = null; w.crossPaid = false; const h0 = T.hourly(w);
    T.staffTrain(w); ok(w.trained === true, 'the course is bought'); const shOf = () => w.shiftNext || w.shift || 'day'; T.staffShiftCycle(w); ok(shOf() === 'early' && (w.shiftNext ? w.shift === 'day' : T.shiftStart(w) === 6), 'the early shift is set (from tomorrow for someone already in today): ' + JSON.stringify({ shift: w.shift, next: w.shiftNext })); T.staffShiftCycle(w); T.staffShiftCycle(w); ok(shOf() === 'day', 'and back to the day shift');
    T.staffRaise(w); ok(w.raise === true && Math.abs(T.hourly(w) - h0 * 1.1) < 0.001 && w.punct === 1, 'the raise: 10% more an hour and punctuality pinned');
    T.staffCrossCycle(w); ok(!!w.cross && w.cross !== w.role && w.crossPaid === true, w.name + ' covers ' + w.cross + ' work as a second role'); w.cross = null;
    const lvS = S.level; S.level = 7; ok(T.staffCap() === 8, 'the crew grows to eight at level 7'); S.level = lvS;
    const pr = T.plantRows(); ok(pr.length >= 6 && pr.some((r) => /Pack line/.test(r.text)) && pr.some((r) => /Sortation deck/.test(r.text)) && pr.some((r) => /Dock loader OUT 3/.test(r.text)), 'the plant page lists ' + pr.length + ' rows, the pack line, the deck and the loaders among them');
    T.openPanel('pc', 'plant'); ok(/Pack line/.test(T.panelHtml()) && /data-act="dial"/.test(T.panelHtml()), 'the panel has a Plant tab with dials'); T.closePanel();
    T.player.x = T.SPOT.pc.x; T.player.z = T.SPOT.pc.z - 1.2; T.openPc(); T.pc.app = 'plant'; if (T.pc.screen) T.pc.screen.dirty = true; T.drawScreens(0.05); ok(T.pc.screen && T.pc.screen.zones.length >= 4, 'the office PC has a Plant app with ' + (T.pc.screen ? T.pc.screen.zones.length : 0) + ' buttons'); T.closePc();
    S.trucks.filter((t) => t.dir === 'in').forEach((t) => T.truckLeave(t, 'test')); T.run(20); const it = T.spawnTruck('in', 0, 23); it.x = -T.HALL.x - 0.4; T.run(3); T.setDoor(0, true); T.run(4); const csc = T.screens.filter((s) => s.title === 'Dock console IN 1')[0]; if (csc) { csc.dirty = true; T.drawScreens(0.05); } const sz = csc && csc.zones.filter((z) => /SIGN THE DELIVERY NOTE/.test(z.label))[0]; ok(!!sz && !it.signed, 'the inbound console offers to sign the note for a docked truck'); if (sz) { sz.act(); } ok(it.signed === true, 'and the note is signed from the console'); T.truckLeave(it, 'test'); T.run(15); }
  // the deck is walkable: a corridor along the wall under the collector, the parcel run overhead across the walkway, step-overs over the pick belt and the spine, the OUT 3 console within reach
  { T.player.y = 4.6; ok(T.floorYAt(0, -23.0, 4.6) === 4.6 && !T.collides(0, -23.0), 'the corridor along the north wall is clear under the collector');
    ok(!T.collides(25.5, -16.0) && !T.collides(27.5, -16.5) && !T.collides(28.2, -16.5), 'the walkway under the overhead parcel run is clear, east to the collector');
    ok(Math.abs(T.floorYAt(22.0, -17.2, 4.6) - 5.6) < 0.01 && Math.abs(T.floorYAt(23.25, -17.2, 4.6) - 5.1) < 0.05 && Math.abs(T.floorYAt(23.35, -20.7, 4.6) - 5.6) < 0.01 && Math.abs(T.floorYAt(23.35, -22.0, 4.6) - 5.04) < 0.05, 'the step-overs: a metre up on the platforms, halfway on the stairs');
    T.player.y = 5.6; ok(!T.collides(22.0, -17.2) && !T.collides(23.35, -20.7), 'standing on a step-over platform clears the belt under it'); T.player.y = 4.6; ok(T.collides(22.0, -15.0) && T.collides(10.0, -20.7), 'and the belts themselves still block a walker on the deck');
    T.player.y = 0; T.player.x = 34.6; T.player.z = -22.3; const ft = T.lookAt(34.6, 1.47, -23.83); ok(/Dock console OUT 3|Open door|Close door|DISPATCH NOW|nothing loaded|air packed/.test(ft || ''), 'the OUT 3 console on the north wall is within reach: ' + ft); }
  // the hand scanner (1.15.0): eight pages draw, the orders page has rows with slots, F sets a waypoint the HUD shows and arriving clears it, the beam reads a slot and a pallet
  { T.player.tool = null; T.releaseTool(); S.hand = null; T.handSet(null); if (T.pc.on) T.closePc(); S.flags.noOrders = 1; const so2 = mkOrder(); so2.state = 'open'; T.scanToggle(true); let threw = null; const counts = [];
    try { for (let pg = 0; pg < 8; pg++) { T.scanPage(pg); counts.push(T.scanRows().length); } } catch (e) { threw = e; } ok(!threw && counts.every((n) => n >= 1), 'all eight scanner pages draw with rows: ' + counts.join(' ') + (threw ? ' threw ' + threw.message : ''));
    T.scanPage(1); const orow = T.scanRows().filter((r) => r.nav)[0]; ok(!!orow && /·/.test(orow.nav.label), 'the orders page offers a slot to go to: ' + (orow && orow.nav.label));
    T.scanPage(2); const pr2 = T.scanRows(); const navRow = pr2.findIndex((r) => r.nav); ok(navRow >= 0, 'the pick list has a row with a slot: ' + (pr2[0] && pr2[0].text)); if (navRow >= 0) { T.scan.sel = navRow; T.scanGo(); ok(!!T.scan.nav && T.scan.nav.label === pr2[navRow].nav.label, 'F set the waypoint: ' + (T.scan.nav && T.scan.nav.label)); T.run(0.2); T.tickScanner(0.1); ok(document.getElementById('h-drive').hidden === false && /m/.test(document.getElementById('h-drive').textContent), 'the HUD shows the heading and the distance: ' + document.getElementById('h-drive').textContent); T.player.x = T.scan.nav.x; T.player.z = T.scan.nav.z; T.player.y = T.scan.nav.y || 0; T.run(0.3); T.tickScanner(0.1); ok(T.scan.nav === null, 'arriving at the waypoint clears it'); }
    const sk5 = T.slotKey(0, 5, 0); S.slots[sk5] = { sku: 'lamps', n: 4, pal: true }; const sp5 = T.rackSlotPos(0, 5, 0); T.player.x = sp5.x; T.player.z = sp5.z - 1.8; T.player.y = 0; T.lookAt(sp5.x, 0.7, sp5.z); const rd1 = T.scanReadout(); ok(!!rd1 && rd1.key === 'slot:' + sk5 && /4 × Desk lamps/.test(rd1.body), 'the beam reads a slot: ' + (rd1 && rd1.head + ' / ' + rd1.body));
    const rpal = T.newPallet('toys', 3, { place: 'floor', x: 0, z: -1.5, y: 0, rot: 0 }); T.player.x = 0; T.player.z = 0.4; T.run(0.05); T.lookAt(0, 0.3, -1.5); const rd2 = T.scanReadout(); ok(!!rd2 && rd2.key === 'pal:' + rpal.id && /3 × Toy robots/.test(rd2.head), 'the beam reads a pallet: ' + (rd2 && rd2.head)); S.pallets.splice(S.pallets.indexOf(rpal), 1); delete S.slots[sk5];
    T.scanToggle(false); S.orders = S.orders.filter((o) => o !== so2); S.flags.noOrders = 0; }
  // one press returns the surplus: boxes on the bench no order wants, and loose boxes on the floor, go back on the racks
  { S.flags.noOrders = 1; S.orders = S.orders.filter((o) => o.state !== 'open'); S.floor = S.floor.filter((f) => f.kind !== 'box'); S.bench.boxes = { paint: 5, bolts: 2 }; S.floor.push({ kind: 'box', sku: 'lamps', x: 0, y: 0, z: 0, rot: 0 }); const st0 = T.stockCount('paint') + T.stockCount('bolts') + T.stockCount('lamps'); ok(T.surplusCount() === 8, 'eight surplus boxes counted: ' + T.surplusCount()); const mv = T.returnSurplus(); ok(mv === 8 && T.benchNeed && Object.keys(S.bench.boxes).length === 0 && T.stockCount('paint') + T.stockCount('bolts') + T.stockCount('lamps') === st0 + 8 && !S.floor.some((f) => f.kind === 'box' && f.sku === 'lamps'), 'all eight went back on the racks in one press'); S.flags.noOrders = 0; }
  // returns (1.16.0): an outbound truck brings a parcel back; off the truck by hand, onto the desk, inspected; the boxes come out resaleable or damaged; the driver leaves one unclaimed inside the door; the packer handles the rest
  { S.flags.noOrders = 1; S.level = Math.max(S.level, 3); S.events.power = false; quietDocks(); S.trucks.filter((t) => t.dir === 'out').forEach((t) => T.truckLeave(t, 'test')); T.run(20);
    const dw = T.propWorld('returnsDesk', 0, 1.1); ok(!!T.propInst.returnsDesk && !T.collides(dw.x, dw.z) && T.insideHall(dw.x, dw.z), 'the returns desk stands between the bench and the office with room to work at it: ' + dw.x.toFixed(1) + ',' + dw.z.toFixed(1));
    const rt = T.spawnTruck('out', 1, 23); rt.x = T.HALL.x + 0.4; const rid = T.addReturn(rt, { num: 77, client: 'grocer', mode: 'land', lines: [{ sku: 'cereal', qty: 2 }], reason: 'unwanted' }); T.run(3); T.setDoor(3, true); T.run(4);
    ok(rt.state === 'docked' && rt.returns.length === 1 && T.returnPlace(rid) === 'truck', 'a return rides in on the land truck');
    T.player.tool = null; T.releaseTool(); S.hand = null; T.handSet(null); const lp = T.loadPrompt(rt.id); ok(/Take return #77/.test(lp || ''), 'the trailer offers the return: ' + lp); T.loadUse(rt.id); ok(S.hand && S.hand.kind === 'return' && S.hand.id === rid && rt.returns.length === 0, 'took the return into the hand');
    T.player.x = dw.x; T.player.z = dw.z; T.rdeskUse(); ok(!S.hand && T.rdesk().queue[0] === rid && T.returnPlace(rid) === 'desk', 'the return is on the desk');
    const bank0 = S.bank; T.rdeskUse(); ok(T.rdesk().s[0].cur === rid, 'E on the desk starts the inspection'); T.run(6); ok(!T.rdesk().s[0].cur && T.rdesk().shelf.length === 2 && T.rdesk().shelf.every((b) => b.sku === 'cereal' && !b.damaged) && S.bank === bank0 + 18 && !T.returnById(rid) && (S.stats.returns || 0) >= 1, 'inspected: two resaleable boxes on the shelf and the $18 fee paid: ' + JSON.stringify({ shelf: T.rdesk().shelf, bank: S.bank - bank0 }));
    T.rdeskBoxUse({ kind: 'rdesk', idx: 0 }); ok(S.hand && S.hand.kind === 'box' && S.hand.sku === 'cereal' && T.rdesk().shelf.length === 1, 'a box off the shelf into the hand'); S.hand = null; T.handSet(null); T.rdesk().shelf.length = 0;
    T.addReturn(rt, { num: 78, client: 'grocer', mode: 'land', lines: [{ sku: 'lamps', qty: 1 }], reason: 'damaged' }); T.loadUse(rt.id); T.rdeskUse(); T.rdeskUse(); T.run(6); ok(T.rdesk().shelf.length === 1 && T.rdesk().shelf[0].damaged, 'a damaged return leaves a damaged box on the shelf');
    T.rdeskBoxUse({ kind: 'rdesk', idx: 0 }); const bank1 = S.bank, binned0 = S.binned || 0, bd2 = T.PROPS.binDamaged; T.player.x = bd2.x - 0.8; T.player.z = bd2.z; T.lookAt(bd2.x, 0.45, bd2.z); T.useFocus(); ok(!S.hand && (S.binned || 0) === binned0 + 1 && S.bank === bank1, 'binned the damaged return at no charge');
    const rid3 = T.addReturn(rt, { num: 79, client: 'grocer', mode: 'land', lines: [{ sku: 'bolts', qty: 1 }], reason: 'wrong' }); T.truckLeave(rt, 'test'); ok(T.returnPlace(rid3) === 'floor' && S.floor.some((f) => f.kind === 'return' && f.id === rid3 && T.insideHall(f.x, f.z)), 'the driver left the unclaimed return on the dock floor inside');
    S.floor = S.floor.filter((f) => f.kind !== 'return' || f.id === rid3); S.trucks.forEach((t) => { t.returns = []; }); S.returns = S.returns.filter((r) => r.id === rid3);   // returns the scheduled trucks left at other doors would be fetched first
    { let pk = S.staff.filter((st) => st.role === 'packer')[0]; if (!pk) { const n0 = S.staff.length; T.hireStaff('packer'); pk = S.staff[n0]; } const t0 = S.time; pk.state = 'idle'; pk.task = null; pk.carry = null; pk.clocked = true; pk.sick = false; pk.dayOff = false; S.bench.parcels.length = 0; S.orders = S.orders.filter((o) => o.state !== 'open'); T.setTime(10); const trace = []; for (let ti = 0; ti < 10; ti++) { T.run(9); trace.push((ti * 9 + 9) + 's ' + pk.state + '/' + (pk.task ? pk.task.kind : '-') + '/' + pk.x.toFixed(0) + ',' + pk.z.toFixed(0) + '/t' + (pk.timer === undefined ? '-' : pk.timer.toFixed(1)) + '/' + (pk.carry ? pk.carry.kind : '-') + '/' + T.returnPlace(rid3)); if (T.returnPlace(rid3) !== 'floor' && T.returnPlace(rid3) !== 'staff') break; } const pl = T.returnPlace(rid3); ok(pl === 'desk' || pl === 'inspecting' || pl === null, 'the packer took the return to the desk when the bench had nothing for them: ' + pl + ' · ' + trace.join(' | ') + ' · shift=' + pk.shift + ' clocked=' + pk.clocked + ' sick=' + pk.sick + ' off=' + pk.dayOff + ' brk=' + pk.state); T.setTime(t0); }
    S.floor = S.floor.filter((f) => f.kind !== 'return'); T.rdesk().shelf.length = 0; T.rdesk().queue.length = 0; T.rdesk().s[0].cur = null; S.returns.length = 0; S.staff.forEach((st) => { if (st.carry && st.carry.kind === 'return') st.carry = null; if (st.task && /^ret|rdesk/.test(st.task.kind)) st.task = null; }); T.run(15); S.flags.noOrders = 0; }
  // the annex halls: shuttered doorways until bought; Hall 2 stands with its rows; Hall 3 brings IN 3 and a truck docks there and is emptied into its rows; Hall 4 opens behind the wing
  { S.bank += 40000; const lvH = S.level; S.level = Math.max(S.level, 8); S.flags.noOrders = 1; S.events.power = false; T.player.y = 0;
    ok(!!T.propInst.shuthall2 && T.collides(18.8, -24.0) && !T.insideHall(20, -34), 'Hall 2 is shuttered and not yet a place');
    S.slots['20,3,0'] = { sku: 'books', n: 5, pal: true }; const hadDesk = !!T.propInst.returnsDesk, booksBefore = T.stockCount ? T.stockCount('books') : 0;   // an old save with stock in Hall 2's row H
    T.buyUpgrade('hall2'); ok(!!S.up.hall2 && !!T.propInst.hall2 && !T.propInst.rack20 && !T.propInst.rack21 && T.insideHall(20, -34) && T.floorYAt(20, -34, 0) === 0, 'bought the returns hall: it stands with no rack rows and is inside');
    ok(!T.collides(18.8, -24.0), 'its doorway is open'); ok(!S.slots['20,3,0'] && T.groundRows().indexOf(20) < 0 && T.slotTotal() === S.up.rows * 45 + (S.up.upper ? 30 : 0), 'the old row H stock moved out and rows 20/21 are no rows: ' + T.slotTotal() + ' slots');
    ok(!!T.propInst.retBelt && !!T.propInst.retIntake && !!T.propInst.retDesk0 && !!T.propInst.retDesk1 && !!T.propInst.retDesk2 && !!T.propInst.retCage && !!T.propInst.retCompactor && !!T.propInst.retPaint && !!T.propInst.retSign, 'the returns hall has its belt, intake, three desks, cage, compactor, paint and sign');
    ok(hadDesk && !T.propInst.returnsDesk && T.returnsHall() && T.rdeskStations() === 3 && T.rdeskCap() === 8 && T.rdesk().s.length === 3, 'the desk by the bench has gone; three stations share a queue of eight');
    ok(S.doors.length === 7 && !!T.doorOwned(6) && T.doorPassable(6) === false && T.collides(36.0, -30.0) && T.dockStepSide(6) === -1 && T.dockStepSide(0) === -1 && T.dockStepSide(1) === 1, 'the returns dock is cut into the east wall, shut, and its steps go north');
    { S.trucks.filter((t) => t.dir !== 'in').forEach((t) => T.truckLeave(t, 'test')); T.run(20); const frozen = S.staff.map((st) => ({ st, state: st.state, clocked: st.clocked, out: st.clockedOutAt })); S.staff.forEach((st) => { st.task = null; st.carry = null; st.state = 'home'; st.clocked = false; st.clockedOutAt = S.time; }); T.rdesk().queue.length = 0; T.rdesk().s.forEach((x) => { x.cur = null; x.t = 0; }); const rt = T.spawnTruck('ret', 0, 23); rt.x = T.HALL.x + 0.4; T.run(3); ok(rt.state === 'docked' && T.truckAtDoor(6) === rt && rt.side === 1 && Math.abs(rt.z - (-34)) < 0.01, 'the returns truck docked at the returns dock on the east side');
      while (rt.returns.length < 3) T.addReturn(rt, { num: 90 + rt.returns.length, client: 'grocer', mode: 'land', lines: [{ sku: 'bolts', qty: 1 }], reason: 'unwanted' }); const nR = rt.returns.length, q0 = T.rdesk().queue.length;
      ok(!T.retFeedWorks(rt), 'the belt does not run with the dock door down'); T.setDoor(6, true); T.run(4); ok(T.retFeedWorks(rt), 'the dock door up and the power on: the belt runs');
      T.run(40); ok(rt.returns.length < nR && (T.rdesk().queue.length > q0 || T.beltItems('retBelt').length > 0), 'the belt takes the returns off the trailer: ' + (nR - rt.returns.length) + ' gone from the truck, ' + T.beltItems('retBelt').length + ' on the belt, queue ' + T.rdesk().queue.length);
      T.run(60); ok(T.rdesk().queue.length >= q0 + 1 && T.beltItems('retBelt').every((it) => it.ret), 'returns off the belt join the intake queue: ' + T.rdesk().queue.length + ' waiting');
      const qid = T.rdesk().queue[0]; ok(T.returnPlace(qid) === 'desk', 'a queued return reads as waiting'); T.rdeskStart(1); ok(T.rdesk().s[1].cur === qid && T.returnPlace(qid) === 'inspecting', 'desk 2 took the next return off the shared queue');
      T.run(6); ok(!T.rdesk().s[1].cur && T.rdesk().shelf.length >= 1, 'desk 2 finished: the boxes are in the restock cage (' + T.rdesk().shelf.length + ')');
      T.truckLeave(rt, 'test'); T.run(1); frozen.forEach((f) => { f.st.state = f.state; f.st.clocked = f.clocked; f.st.clockedOutAt = f.out; }); }
    ok(T.groundRows().indexOf(22) < 0 && T.slotTotal() === S.up.rows * 45 + (S.up.upper ? 30 : 0), 'before Hall 3 the ground rows are the main rows only: ' + S.up.rows + ' main rows, Hall 2 and the deck');
    T.buyUpgrade('hall3'); ok(!!S.up.hall3 && !!T.propInst.hall3 && !!T.propInst.rack22 && T.doorPassable(5) === false && S.doors.length === 7 && !!T.propInst.consoleIn2, 'bought Hall 3: it stands with IN 3 cut into its west wall and a console');
    S.trucks.filter((t) => t.dir === 'in').forEach((t) => T.truckLeave(t, 'test')); T.run(20); const t3 = T.spawnTruck('in', 2, 23); t3.x = -T.HALL.x - 0.4; T.run(3); ok(t3.state === 'docked' && T.truckAtDoor(5) === t3, 'an inbound truck docked at IN 3'); T.setDoor(5, true); T.run(4); T.signTruck(t3); ok(T.doorPassable(5) && t3.signed, 'IN 3 opened and the note is signed');
    S.staff.forEach((st) => { st.task = null; st.carry = null; if (st.state === 'idle' || st.state === 'wait') st.state = 'idle'; }); const put3 = S.stats.putaway, left0 = S.pallets.filter((p) => p.place === 'truck' && p.truck === t3.id && p.n > 0).length; T.setTime(10); T.run(240); const left1 = S.pallets.filter((p) => p.place === 'truck' && p.truck === t3.id && p.n > 0).length; ok(left1 < left0, 'the crew walked into Hall 3 and emptied the IN 3 truck: ' + left0 + ' pallets to ' + left1 + ', putaway +' + (S.stats.putaway - put3)); T.truckLeave(t3, 'test'); T.run(15);
    T.buyUpgrade('hall4'); ok(!!S.up.hall4 && !!T.propInst.hall4 && T.insideHall(0, -54) && !T.collides(6.8, -44.0) && T.collides(2.0, -44.0), 'bought Hall 4 behind the wing: inside, its doorway through the wing wall open, the wall beside it solid');
    T.player.y = 0; ok(!T.collides(18.8, -23.6) && !T.collides(18.8, -24.4), 'the Hall 2 doorway is clear on both faces of the wall (no lining across it)');
    ok(!T.solids.some((s) => !s.prop && s.x0 > 35 && s.z1 > -23.4 && s.z0 < -19.8 && s.y0 < 1 && s.y1 > 5), 'no lining column stands in the OUT 3 doorway');
    ok(T.solids.some((s) => s.prop === 'hall2' && s.y1 > 7) && !!T.propInst.exthall2 && !!T.propInst.clockhall2 && !T.propInst.aislehall2, 'the returns hall has its columns, extinguisher and clock, and no aisle sign');
    S.flags.noOrders = 0; S.level = lvH; }
  // the scanner's map page draws; photo mode frees the camera and hides the HUD; the day report closes the day
  { T.scanToggle(true); let threw = null; try { T.scanPage(T.MAP_PAGE); T.drawScanner(); } catch (e) { threw = e; } ok(!threw && T.scan.page === T.MAP_PAGE && T.scanRows().length === 0, 'the map page draws without rows' + (threw ? ': ' + threw.message : '')); T.scanPage(0); T.scanToggle(false);
    T.photoToggle(true); ok(T.photo.on && document.getElementById('dc-hud').hidden === true, 'F9 photo mode: the HUD goes'); const px0 = T.photo.x; T.player.keys.KeyW = true; T.photoTick(0.5); T.player.keys.KeyW = false; ok(Math.abs(T.photo.x - px0) > 0.01 || Math.abs(T.photo.z) > 0, 'W flies the camera forward'); T.photoToggle(false); ok(!T.photo.on && document.getElementById('dc-hud').hidden === false, 'and F9 again puts the HUD back');
    const d0 = (S.days || []).length; T.closeDay(); T.closeDay(); ok(S.days.length >= d0 + 1 && S.days[0].day === S.day && typeof S.days[0].net === 'number' && T.dayReportShown(), 'closing a day keeps its report and shows the card: ' + JSON.stringify(S.days[0])); document.dispatchEvent(new KeyboardEvent('keydown', { code: 'KeyQ', bubbles: true })); ok(!T.dayReportShown(), 'any key dismisses the card'); }
  // the cold-review fixes: an order shipped by the truck that leaves at its due hour is on time; a box taken off a truck pallet by hand leaves the pallet aboard; the console names the next window that still has a truck to come; jack 2 reads the racks like jack 1
  { const lo = mkOrder(); lo.due = S.day * 24 + S.time; ok(!T.orderLate(lo), 'an order due now is not late'); S.time += 0.04; ok(!T.orderLate(lo), 'nor a tick past its hour'); S.time += 0.1; ok(T.orderLate(lo), 'but it is late a few minutes on'); S.time -= 0.14; S.orders = S.orders.filter((o) => o !== lo);
    S.trucks.filter((t) => t.dir === 'in').forEach((t) => T.truckLeave(t, 'test')); T.run(20); const ht = T.spawnTruck('in', 0, 23); ht.x = -T.HALL.x - 0.4; T.run(3); T.setDoor(0, true); T.run(4); T.signTruck(ht); const hp = T.newPallet('bolts', 4, { place: 'truck', truck: ht.id, idx: ht.pallets.length, x: 0, z: 0 }); ht.pallets.push(hp.id); T.player.tool = null; T.releaseTool(); S.hand = null; T.handSet(null); const rec0 = S.stats.received; T.palletUse({ kind: 'pallet', id: hp.id }); ok(S.hand && S.hand.sku === 'bolts' && hp.place === 'truck' && hp.n === 3 && hp.recv === 1 && S.stats.received === rec0 + 1, 'a box by hand leaves the pallet on the truck, paid once: ' + JSON.stringify({ place: hp.place, n: hp.n })); T.palletUse({ kind: 'pallet', id: hp.id }); S.hand = null; T.handSet(null); T.palletUse({ kind: 'pallet', id: hp.id }); ok(S.stats.received === rec0 + 1 && hp.n === 2, 'the fee is not paid again'); S.hand = null; T.handSet(null); T.truckLeave(ht, 'test'); T.run(15);
    { const t0 = S.time; T.setTime(9.5); delete S.flags['out' + S.day + '-1-1']; S.flags['out' + S.day + '-1-0'] = 1; ok(T.outNext(1).arrive === 16 && !T.outNext(1).tomorrow, 'with the morning land truck gone the console says the afternoon window'); S.flags['out' + S.day + '-1-1'] = 1; ok(T.outNext(1).tomorrow === true, 'and tomorrow once both have been'); T.setTime(t0); }
    const jk2 = T.slotKey(1, 6, 0); S.slots[jk2] = { sku: 'books', n: 4, pal: true }; T.player.tool = 'jack2'; S.jack2.pallet = null; ok(/Pull the pallet out/.test(T.slotPrompt(jk2) || ''), 'jack 2 is offered the pallet like jack 1: ' + T.slotPrompt(jk2)); T.player.tool = null; delete S.slots[jk2]; }
  // the PC taskbar holds ten apps in two rows, every button whole and inside the screen
  { T.player.x = T.SPOT.pc.x; T.player.z = T.SPOT.pc.z - 1.2; T.openPc(); T.pc.app = 'home'; if (T.pc.screen) T.pc.screen.dirty = true; T.drawScreens(0.05); const zs = T.pc.screen ? T.pc.screen.zones.filter((z) => /Plant|Desktop|Orders|Stats/.test(z.label)) : []; const plant = zs.filter((z) => /Plant/.test(z.label))[0]; ok(!!plant && plant.w >= 140 && plant.x + plant.w <= 800 && plant.y + plant.h <= 500, 'the Plant app button is ' + (plant ? plant.w + ' px wide at ' + plant.x + ',' + plant.y : 'missing')); T.closePc(); }
  // the order board: more than seven orders make pages, the wheel holds a page for a while
  { S.flags.noOrders = 1; const made = []; for (let i = 0; i < 9; i++) { const ob = T.genOrder(false); if (ob) { if (ob.state !== 'open') ob.state = 'open'; made.push(ob); } } const bsc = T.screens.filter((s) => s.title === 'Order board')[0]; if (bsc) { bsc.dirty = true; T.drawScreens(0.05); } const openN = S.orders.filter((o) => o.state === 'open' || o.state === 'packed').length; ok(!!bsc && bsc.scrollable && bsc.scrollMax === Math.ceil(openN / 7) - 1, 'the order board has ' + (bsc ? bsc.scrollMax + 1 : 0) + ' pages for ' + openN + ' orders'); if (bsc && bsc.scrollMax >= 1) { bsc.scroll = 1; bsc.userScrollAt = 1e9; bsc.dirty = true; T.drawScreens(0.05); ok(bsc.scroll === 1, 'the wheel holds the board on page 2'); bsc.userScrollAt = 0; } made.forEach((ob) => { const k = S.orders.indexOf(ob); if (k >= 0) S.orders.splice(k, 1); }); S.flags.noOrders = 0; }
  // the cranes and the pickers share one in-flight ledger: a picker's claim, or a box already on the belt, covers the demand and the crane stands down
  { S.flags.noOrders = 1; const gk3 = T.slotKey(0, 4, 0); for (const k in S.slots) if (S.slots[k] && S.slots[k].sku === 'paint') delete S.slots[k]; S.pallets.forEach((p) => { if (p.sku === 'paint') p.sku = 'bolts'; }); S.staff.forEach((st) => { if (st.carry && st.carry.sku === 'paint') st.carry = null; if (st.task && st.task.sku === 'paint') st.task = null; }); S.slots[gk3] = { sku: 'paint', n: 3, pal: true }; S.bench.boxes = {}; T.beltItems('pickBelt').length = 0; T.beltItems('pickMerge').length = 0; const go4 = T.genOrder(false); go4.lines = [{ sku: 'paint', qty: 1 }]; S.orders = S.orders.filter((o) => o === go4 || o.state !== 'open'); T.gantryState(0).state = 'idle'; T.gantryState(0).sku = null; T.gantryState(1).state = 'idle'; T.gantryState(1).sku = null;
    ok(!!T.gantryNeed(0) && T.gantryNeed(0).sku === 'paint', 'crane A sees one paint box wanted');
    if (!S.staff.length) T.hireStaff('picker'); const claimer = S.staff[0], oldTask = claimer.task, oldCarry = claimer.carry; claimer.carry = null; claimer.task = { kind: 'pick', sku: 'paint', key: gk3 };
    ok(T.gantryNeed(0) === null, 'a picker walking to the slot has claimed it: crane A stands down');
    claimer.task = oldTask; claimer.carry = oldCarry; T.beltItems('pickBelt').push({ kind: 'box', sku: 'paint', d: 1 });
    ok(T.gantryNeed(0) === null, 'a paint box already riding the pick belt covers the demand too');
    T.beltItems('pickBelt').length = 0; S.flags.noOrders = 0; }
  T.beltItems('pickBelt').length = 0; T.beltItems('pickBelt').push({ kind: 'box', sku: 'coffee', d: 17.2 }); S.hand = null; T.handSet(null); T.run(0.1); const bw = T.beltPoint(T.BELTS.pickBelt, 17.2); T.player.x = bw.x - 1.2; T.player.z = bw.z; T.lookAt(bw.x, bw.y + 0.17, bw.z); ok(/off the belt/.test(T.focusText()), 'looking at a box on the pick belt offers to take it: ' + T.focusText()); T.useFocus(); ok(S.hand && S.hand.kind === 'box' && S.hand.sku === 'coffee' && T.beltItems('pickBelt').length === 0, 'took the coffee box off the pick belt by hand'); S.hand = null; T.handSet(null); S.flags.noOrders = 0; ok(!T.propInst.pickBelt2 && !T.propInst.gantry3 && !T.propInst.gantry4, 'with three rows there is no north belt and no crane over rows D to F'); { const rows1 = S.up.rows; S.up.rows = 6; T.buildGantries(); const bays = [['jack', T.SPOT.jack, 0.8, 1.1], ['cart', T.SPOT.cart, 0.9, 0.7]]; bays.forEach((b) => { const hit = T.solids.filter((s) => s.x0 < b[1].x + b[2] && s.x1 > b[1].x - b[2] && s.z0 < b[1].z + b[3] && s.z1 > b[1].z - b[3] && s.y0 < 1.5 && !/jack|cart/.test(String(s.tag || s.prop || ''))); ok(hit.length === 0, 'the ' + b[0] + ' bay at ' + b[1].x + ',' + b[1].z + ' is clear of every solid with all six cranes up' + (hit.length ? ': ' + JSON.stringify(hit.slice(0, 2)) : '')); }); S.up.rows = rows1; } T.drawScreens(0.05); const gsc = T.MACH.gantry1.screen; ok(gsc && gsc.zones.length === 4, 'the crane B cabinet screen draws with four buttons (pause, reset, two dials): ' + (gsc ? gsc.zones.map((z) => z.label).join('/') : 'none')); const pz = gsc.zones.filter((z) => z.label === 'PAUSE')[0]; ok(!!pz, 'the first button is PAUSE'); if (pz) { pz.act(); ok(T.gantryState(1).paused === true, 'tapping PAUSE holds crane B'); T.run(0.1); T.drawScreens(0.05); ok(gsc.zones.some((z) => z.label === 'RESUME'), 'the button now reads RESUME'); T.gantryState(1).paused = false; } const rows0 = S.up.rows; S.up.rows = 5; T.buildGantries(); ok(!!T.propInst.gantry4 && !!T.propInst.pickBelt2 && T.beltSink(T.BELTS.pickBelt2) && T.beltSink(T.BELTS.pickBelt2).belt && T.beltSink(T.BELTS.pickBelt2).belt.id === 'pickMerge', 'the fifth row brings its crane and the north pick belt, which joins the same merge belt: ' + JSON.stringify({ g4: !!T.propInst.gantry4, pb2: !!T.propInst.pickBelt2, sink: (function () { const k = T.beltSink(T.BELTS.pickBelt2); return k ? (k.belt ? 'belt ' + k.belt.id : 'machine ' + k.machine.id) : null; })(), end: (function () { const b = T.BELTS.pickBelt2, L = b.path.reduce((acc, p, i) => i ? acc + Math.hypot(p[0] - b.path[i - 1][0], p[1] - b.path[i - 1][1]) : 0, 0); const e = T.beltPoint(b, L); return [+e.x.toFixed(2), +e.z.toFixed(2)]; })(), mergeStart: (function () { const e = T.beltPoint(T.BELTS.pickMerge, 0); return [+e.x.toFixed(2), +e.z.toFixed(2)]; })() })); T.run(0.2); S.up.rows = rows0;
  // film follows a wrapped pallet onto the rack and comes back with it; the forklift lifts an empty pallet out of a slot
  const wk = T.slotKey(0, 5, 0); delete S.slots[wk]; const wrP = T.newPallet('toys', 2, { place: 'floor', x: 0, z: 0, y: 0, rot: 0, wrapped: true }); ok(T.storePallet(wrP, wk) && S.slots[wk].wrapped, 'a wrapped pallet keeps its film on the rack'); S.fork.x = 0; S.fork.z = 0;
  S.slots[wk].n = 0; S.fork.lift = 0.1; S.fork.pallet = null; const sp0 = T.rackSlotPos ? null : null; T.player.x = -8; T.player.z = T.RACK.rows[0] - 1.6; S.fork.x = -7.5; S.fork.z = T.RACK.rows[0] - 1.6; S.fork.yaw = 0; T.startDrive(); T.forkUse(); T.stopDrive(); ok(S.fork.pallet && T.palletById(S.fork.pallet).n === 0 && !S.slots[wk], 'the forklift lifts the empty pallet out of a slot'); S.fork.pallet = null;
  // two jacks: jack 2 lifts a pallet out of a slot and parks again with it; the aisles between the rows stay wide enough for the forklift
  { T.player.tool = null; T.releaseTool(); const j2 = T.SPOT.jack2; ok(Math.abs(S.jack2.x - j2.x) < 0.01 && !S.jack2.pallet, 'jack 2 waits in its bay by the OUT docks at ' + j2.x + ',' + j2.z); const jk = T.slotKey(0, 4, 0); S.slots[jk] = { sku: 'books', n: 5, pal: true }; const jpos = T.rackSlotPos(0, 4, 0); T.player.x = jpos.x; T.player.z = jpos.z - 1.8; T.grabTool('jack2'); ok(T.player.tool === 'jack2', 'grabbed jack 2'); T.slotUse(jk); const jp2 = S.jack2.pallet ? T.palletById(S.jack2.pallet) : null; ok(jp2 && jp2.place === 'jack' && jp2.jack === 'jack2' && S.jack.pallet !== S.jack2.pallet, 'jack 2 pulled the pallet and jack 1 is untouched: ' + JSON.stringify({ j2: S.jack2.pallet, place: jp2 && jp2.place, jk: jp2 && jp2.jack, j1: S.jack.pallet })); const pw2 = T.palletWorld ? T.palletWorld(jp2) : null; T.releaseTool(); ok(!T.player.tool && S.jack2.pallet === jp2.id, 'jack 2 parked with its pallet still on it'); S.jack2.pallet = null; jp2.place = 'floor'; jp2.x = S.jack2.x; jp2.z = S.jack2.z; S.jack2.x = j2.x; S.jack2.z = j2.z; }
  { let minGap = 99; for (let r = 0; r < S.up.rows - 1; r++) { let top = -99, bot = 99; T.solids.forEach((s) => { if (s.y0 > 2.2 || s.x0 > 21 || s.x1 < -24) return; if (s.prop === 'rack' + r || s.prop === 'gantry' + r) top = Math.max(top, s.z1); if (s.prop === 'rack' + (r + 1) || s.prop === 'gantry' + (r + 1)) bot = Math.min(bot, s.z0); }); minGap = Math.min(minGap, bot - top); } ok(minGap >= 4.6, 'the narrowest aisle between rows is ' + minGap.toFixed(2) + ' m clear, with the cranes up'); } { let fTop = -99, aBot = 99; T.solids.forEach((s) => { if (s.y0 > 2.2) return; if (s.prop === 'rack5' || s.prop === 'gantry5') fTop = Math.max(fTop, s.z1); if (s.prop === 'rack0' || s.prop === 'gantry0') aBot = Math.min(aBot, s.z0); }); ok(18.5 - fTop >= 2.0 && aBot - -20.2 >= 1.6, 'row F and its crane end ' + (18.5 - fTop).toFixed(2) + ' m short of the office front; row A ends ' + (aBot - -20.2).toFixed(2) + ' m short of the break room'); }
  // the AGV dock screen pauses the AGV; the bench terminal scrolls its order list
  { T.drawScreens(0.05); const asc = T.agvScreen(); ok(asc && asc.zones.some((z) => z.label === 'PAUSE'), 'the AGV dock screen offers PAUSE'); if (asc) { asc.zones.filter((z) => z.label === 'PAUSE')[0].act(); ok(T.agvState().paused === true, 'PAUSE holds the AGV'); T.agvState().paused = false; } }
  { S.flags.noOrders = 1; for (let i = 0; i < 7; i++) { const og = T.genOrder(false); if (og && og.state !== 'open') og.state = 'open'; } const bsc = T.screens.filter((s) => s.title === 'Bench terminal')[0]; if (bsc) { bsc.dirty = true; } T.drawScreens(0.05); ok(bsc && bsc.scrollable && bsc.scrollMax >= 2, 'the bench terminal has ' + (bsc ? bsc.scrollMax + 4 : 0) + ' orders and scrolls: open=' + S.orders.filter((o) => o.state === 'open').length + ' total=' + S.orders.length + ' max=' + (bsc && bsc.scrollMax)); if (bsc) { const dn = bsc.zones.filter((z) => z.label === 'DOWN')[0]; ok(!!dn, 'the terminal shows a DOWN button'); if (dn) { dn.act(); bsc.dirty = true; T.drawScreens(0.05); ok(bsc.scroll === 1, 'DOWN scrolled the list by one'); } } S.flags.noOrders = 0; }
  // speed dials: the pick belt runs twice as fast at 200 percent; the crane screen cycles its dial
  { T.beltItems('pickBelt').length = 0; S.speed = {}; T.beltItems('pickBelt').push({ kind: 'box', sku: 'bolts', d: 0 }); T.run(2); const d1 = T.beltItems('pickBelt')[0].d; T.beltItems('pickBelt')[0].d = 0; S.speed.pickBelt = 2; T.run(2); const d2 = T.beltItems('pickBelt')[0].d; ok(Math.abs(d1 - 1.0) < 0.15 && Math.abs(d2 - 2.0) < 0.2, 'the pick belt moved ' + d1.toFixed(2) + ' m in 2 s at 100% and ' + d2.toFixed(2) + ' m at 200%'); T.beltItems('pickBelt').length = 0; S.speed = {}; T.drawScreens(0.05); const gsc2 = T.MACH.gantry0.screen; const sb = gsc2.zones.filter((z) => z.label === '100%' && z.y === 152)[0]; ok(!!sb, 'crane A screen shows its crane dial at 100%: ' + gsc2.zones.map((z) => z.label).join('/')); if (sb) { sb.act(); ok(T.speedOf('gantry0') === 1.5, 'one tap takes the crane to 150%'); } S.speed = {}; }
  { const z0 = T.RACK.rows[0]; T.player.x = 23.2; T.player.z = z0 - 3.0; T.player.tool = null; T.gantryState(0).paused = false; T.drawScreens(0.05); const smesh = T.MACH.gantry0.screen.mesh; smesh.updateWorldMatrix(true, false); const swp = new THREE.Vector3(); smesh.getWorldPosition(swp); T.player.x = swp.x; T.player.z = swp.z - 1.6; T.lookAt(swp.x + 0.11, swp.y - 0.08, swp.z); T.interact(); ok(T.focusText() === 'PAUSE', 'aiming at the crane A screen from the aisle focuses the PAUSE button, not the cabinet: ' + JSON.stringify({ focus: T.focusText(), screen: swp.toArray().map((v) => +v.toFixed(2)), player: [T.player.x, T.player.z], vis: smesh.visible, zones: T.MACH.gantry0.screen.zones.length })); T.useFocus(); ok(T.gantryState(0).paused === true, 'E on the screen pauses crane A'); T.gantryState(0).paused = false; }
  // the forklift corridors: east of the cranes and west of the racks, nothing within a forklift radius for the full length of the racks
  { const R = 1.0, low = T.solids.filter((s) => s.y0 <= 2.5); const blockedAt = (x, z) => low.filter((s) => x > s.x0 - R && x < s.x1 + R && z > s.z0 - R && z < s.z1 + R).map((s) => s.prop || 'wall'); let bad = []; for (let z = -16; z <= 16; z += 1) { const e = blockedAt(25.5, z), w = blockedAt(-27.5, z); if (e.length) bad.push('E ' + z + ':' + e[0]); if (w.length) bad.push('W ' + z + ':' + w[0]); } ok(bad.length === 0, 'the east lane at x 25.5 and the west lane at x -27.5 are clear for the forklift from z -16 to 16' + (bad.length ? ': ' + bad.slice(0, 6).join(', ') : '')); }
  // empties: jack 2 takes a pallet off the stack, two loose boxes go on it, the bin writes the load off, the empty pallet stores in a slot and takes a box again
  { S.emptiesN = 2; T.player.tool = null; T.releaseTool(); S.jack2.pallet = null; S.hand = null; T.handSet(null); const em = T.propInst.empties.g.position; T.player.x = em.x; T.player.z = em.z + 1.9; T.grabTool('jack2'); T.lookAt(em.x, 0.8, em.z); T.interact(); ok(/Take an empty pallet/.test(T.focusText()), 'an empty jack at the stack offers a pallet: ' + T.focusText()); T.useFocus(); const ep = S.jack2.pallet ? T.palletById(S.jack2.pallet) : null; ok(ep && ep.n === 0 && S.emptiesN === 1 && ep.jack === 'jack2', 'jack 2 took an empty pallet off the stack');
    if (ep) { T.releaseTool(); S.hand = { kind: 'box', sku: 'lamps' }; T.handSet(S.hand); ok(/empty pallet/.test(T.palletPrompt({ kind: 'pallet', id: ep.id }) || ''), 'a loose box can go on the empty pallet: ' + T.palletPrompt({ kind: 'pallet', id: ep.id })); T.palletUse({ kind: 'pallet', id: ep.id }); S.hand = { kind: 'box', sku: 'lamps' }; T.handSet(S.hand); T.palletUse({ kind: 'pallet', id: ep.id }); ok(ep.n === 2 && ep.sku === 'lamps' && !S.hand, 'two loose boxes stacked on the pallet by hand'); S.hand = { kind: 'box', sku: 'paint' }; T.handSet(S.hand); T.palletUse({ kind: 'pallet', id: ep.id }); ok(ep.n === 2 && !!S.hand, 'a box of another line stays in hand'); S.hand = null; T.handSet(null);
      T.grabTool('jack2'); const bn = T.propInst.binDamaged.g.position; T.player.x = bn.x; T.player.z = bn.z + 1.5; T.lookAt(bn.x, 0.45, bn.z); T.interact(); ok(/Write off the whole pallet/.test(T.focusText()), 'the bin offers to write off the pallet load: ' + T.focusText()); const binned1 = S.binned || 0, bank1 = S.bank; T.useFocus(); ok(ep.n === 0 && (S.binned || 0) === binned1 + 2 && S.bank < bank1, 'the two boxes were written off and the pallet is empty again');
      const ek = T.slotKey(2, 3, 0); delete S.slots[ek]; T.slotUse(ek); ok(S.slots[ek] && S.slots[ek].pal && S.slots[ek].n === 0 && !S.jack2.pallet, 'the empty pallet stores in a floor slot'); T.releaseTool(); S.hand = { kind: 'box', sku: 'toys' }; T.handSet(S.hand); T.slotUse(ek); ok(S.slots[ek].n === 1 && S.slots[ek].sku === 'toys' && !S.hand, 'a box by hand goes onto the racked empty pallet and sets its line'); delete S.slots[ek]; }
    S.jack2.x = T.SPOT.jack2.x; S.jack2.z = T.SPOT.jack2.z; }
  // the cart unloads its boxes onto a pallet: the matching line onto a loaded one, its biggest line onto an empty one
  { T.player.tool = null; T.releaseTool(); S.up.cart = true; S.cart.boxes = ['toys', 'toys', 'books']; const cp = T.newPallet(null, 0, { place: 'floor', x: 0, z: 0, y: 0, rot: 0 }); T.grabTool('cart'); ok(/Unload 2 × Toy robots/.test(T.palletPrompt({ kind: 'pallet', id: cp.id }) || ''), 'the cart offers its biggest line to an empty pallet: ' + T.palletPrompt({ kind: 'pallet', id: cp.id })); T.palletUse({ kind: 'pallet', id: cp.id }); ok(cp.n === 2 && cp.sku === 'toys' && S.cart.boxes.length === 1 && S.cart.boxes[0] === 'books', 'two toys went onto the pallet, the book stayed on the cart'); ok(/Take a box of Toy robots/.test(T.palletPrompt({ kind: 'pallet', id: cp.id }) || ''), 'with no matching boxes left the cart picks from the pallet again'); T.releaseTool(); S.cart.boxes = []; T.removePallet ? T.removePallet(cp.id) : (cp.n = 0); }
  // G at the parked cart: take the top box into the hand, put it back
  { T.player.tool = null; T.releaseTool(); S.up.cart = true; S.cart.boxes = ['paint', 'books']; S.hand = null; T.handSet(null); S.cart.x = -10; S.cart.z = -1.0; S.cart.rot = 0; T.run(0.1); const cw = T.toolWorld('cart'); T.player.x = cw.x; T.player.z = cw.z + 1.6; T.lookAt(cw.x, 0.7, cw.z); T.interact(); ok(/G takes one off/.test(T.focusText()), 'the parked cart offers a box on G: ' + T.focusText()); T.focusAlt(); ok(S.hand && S.hand.sku === 'books' && S.cart.boxes.length === 1, 'G took the top box (books) into the hand'); T.interact(); ok(/G puts the box on the cart/.test(T.focusText()), 'with a box in hand the cart offers to take it: ' + T.focusText()); T.focusAlt(); ok(!S.hand && S.cart.boxes.length === 2, 'G put the box back on the cart'); S.cart.boxes = []; }
  // parcels ride the cart: two off the shelf onto the cart, both into a docked outbound truck in one go
  { T.player.tool = null; T.releaseTool(); S.cart.boxes = []; T.cartParcels().length = 0; S.hand = null; T.handSet(null); const po = [T.genOrder(false), T.genOrder(false)]; po.forEach((o) => { o.state = 'packed'; if (S.bench.parcels.indexOf(o.id) < 0) S.bench.parcels.push(o.id); }); T.grabTool('cart'); ok(/Load parcel #/.test(T.shelfPrompt({ kind: 'shelf', order: po[0].id }) || ''), 'the shelf offers a parcel to the cart: ' + T.shelfPrompt({ kind: 'shelf', order: po[0].id })); T.shelfUse({ kind: 'shelf', order: po[0].id }); T.shelfUse({ kind: 'shelf', order: po[1].id }); ok(T.cartParcels().length === 2 && S.bench.parcels.indexOf(po[0].id) < 0, 'two parcels went from the shelf onto the cart');
    S.trucks.filter((t) => t.dir === 'out').forEach((t) => T.truckLeave(t, 'test')); T.run(4); const ct = T.spawnTruck('out', 0, 18); ct.x = T.HALL.x + 0.4; T.run(3); T.setDoor(2, true); T.run(3); ok(ct.state === 'docked' && /Unload 2 parcels from the cart/.test(T.loadPrompt(ct.id) || ''), 'the trailer offers to take both parcels off the cart: ' + T.loadPrompt(ct.id)); T.loadUse(ct.id); ok(T.cartParcels().length === 0 && ct.parcels.indexOf(po[0].id) >= 0 && ct.parcels.indexOf(po[1].id) >= 0 && po[0].state === 'loaded', 'both parcels are in the truck and the orders are loaded'); T.releaseTool(); T.setDoor(2, false); }
  // the drop marker shows where G puts a held box down
  { T.player.tool = null; T.releaseTool(); S.hand = null; T.handSet(null); T.updateDropMarker(); ok(T.dropMarker.g.visible === false, 'no marker with empty hands'); S.hand = { kind: 'box', sku: 'paint' }; T.handSet(S.hand); T.player.x = 0; T.player.z = 0; T.player.yaw = 0; T.updateDropMarker(); const dp = T.dropPoint(); ok(T.dropMarker.g.visible && T.dropMarker.box.visible && !T.dropMarker.par.visible && Math.abs(T.dropMarker.g.position.x - dp.x) < 0.01 && Math.abs(T.dropMarker.g.position.z - dp.z) < 0.01 && dp.good, 'holding a box shows the green ghost box at the drop point ' + dp.x.toFixed(2) + ',' + dp.z.toFixed(2)); S.hand = { kind: 'parcel', order: 'x' }; T.handSet(S.hand); T.updateDropMarker(); ok(T.dropMarker.par.visible && !T.dropMarker.box.visible, 'a parcel in hand shows the parcel ghost'); S.hand = null; T.handSet(null); T.updateDropMarker(); ok(!T.dropMarker.g.visible, 'the marker goes when the hands empty'); }
  const cardB = S.baler.card; T.addWaste(10); T.balerUse(); ok(S.baler.t > 0 && S.baler.card === cardB, 'baler started on ten cardboard (offcuts already in the chamber: ' + cardB + ')'); T.run(9); ok(S.baler.bales === 1, 'a bale came out');
  S.hand = { kind: 'box', sku: 'paint', damaged: true }; T.handSet(S.hand); const bd = T.PROPS.binDamaged; T.player.x = bd.x - 0.8; T.player.z = bd.z; const binned0 = S.binned || 0; T.lookAt(bd.x, 0.45, bd.z); T.useFocus(); ok((S.binned || 0) === binned0 + 1 && !S.hand, 'damaged box binned (bin at ' + bd.x.toFixed(1) + ',' + bd.z.toFixed(1) + ')');
  // the office PC: sit down, the screen draws, stand up
  T.openPc(); ok(T.pc.on === true, 'sat down at the PC'); T.run(1); ok(T.pc.screen && T.pc.screen.zones.length > 5, 'the PC screen has ' + (T.pc.screen ? T.pc.screen.zones.length : 0) + ' buttons'); T.closePc(); ok(T.pc.on === false, 'stood up from the PC');
  // build mode: grab the cot, move it, turn it, put it back, remove and restore, buy a chair
  T.player.x = -26; T.player.z = -21.5; T.player.y = 0; T.editToggle(); ok(T.edit.on === true, 'build mode on');
  const cot0 = { x: T.propInst.cot.P.x, z: T.propInst.cot.P.z };
  T.editGrab('cot'); ok(T.edit.grabbed === 'cot', 'grabbed the cot');
  T.propInst.cot.g.position.set(-16, 0, -11); T.editDrop(false); ok(S.layout.cot && Math.abs(S.layout.cot.x + 16) < 0.01, 'cot placed and saved: ' + JSON.stringify(S.layout.cot));
  T.editReset('cot'); ok(!S.layout.cot && Math.abs(T.propInst.cot.P.x - cot0.x) < 0.01, 'cot put back');
  T.edit.grabbed = null; S.layout.cot = { hidden: true }; T.buildProp('cot'); ok(!T.propInst.cot, 'a removed prop is off the instance list');
  T.editRestore('cot'); ok(T.propInst.cot.g.children.length > 0, 'cot restored');
  const bank4 = S.bank; T.editBuy('xChair'); ok(S.custom.length === 1 && S.bank === bank4 - 25 && T.edit.grabbed === S.custom[0].id, 'bought a chair and carrying it');
  T.editDrop(false); ok(T.propInst[S.custom[0].id] && !T.edit.grabbed, 'chair placed'); T.edit.grabbed = null;
  T.editToggle(); ok(T.edit.on === false, 'build mode off, layout saved');
  // events
  T.flipBreaker(); S.events.power = true; T.flipBreaker(); ok(S.events.power === false, 'breaker resets a power cut');
  T.setDoor(1, true); S.events.prowled = false; const stock0 = T.totalStock(); T.setTime(22.9); T.run(10); ok(T.totalStock() < stock0, 'prowler took stock through the open door');
  T.setDoor(1, false); T.setDoor(0, false); T.setDoor(2, false);
  // the crew still in at the day roll go home (a sleep at 17:00 with the day shift in, a late shift at midnight) instead of standing frozen from then on
  { const w0 = S.staff[0]; if (w0) { w0.state = 'idle'; w0.clocked = true; w0.task = null; w0.carry = null; T.setTime(23.98); T.run(2); ok(w0.state === 'home' && !w0.clocked, 'a worker still in at the day roll is sent home: ' + w0.state); } }
  // a full day on the clock, then sleep
  T.run(620); ok(S.day >= 2, 'the clock rolled to day ' + S.day);
  // removing a belt piece with items on it: carried or placed, no throw, the items land on the floor, the registry forgets the piece
  { S.bank += 5000; if (!T.edit.on) T.editToggle(); const fl0 = S.floor.length, cid0 = (S.custom || []).map((c) => c.id); let threw = null;
    try { T.editBuy('xBeltS2'); const idA = T.edit.grabbed; ok(!!idA && !!T.BELTS[idA], 'bought a belt piece and am carrying it: ' + idA); T.beltItems(idA).push({ kind: 'box', sku: 'bolts', d: 0.5 }); T.editRemove(idA); ok(!T.BELTS[idA] && !(S.belts && S.belts[idA]) && !T.propInst[idA] && S.floor.length === fl0 + 1, 'removed the carried piece: box on the floor, piece gone from the registry');
      T.editBuy('xBeltS2'); const idB = T.edit.grabbed; T.editDrop(false); ok(!T.edit.grabbed && !!T.propInst[idB], 'placed a second piece'); T.beltItems(idB).push({ kind: 'parcel', order: 'x-test', d: 1.0 }); const bp = T.beltPoint(T.BELTS[idB], 1.0); T.editRemove(idB); const last = S.floor[S.floor.length - 1]; ok(!T.BELTS[idB] && S.floor.length === fl0 + 2 && last && last.kind === 'parcel' && Math.hypot(last.x - bp.x, last.z - bp.z) < 0.05, 'removed the placed piece: parcel set down where it rode'); }
    catch (e) { threw = e; } ok(!threw, 'removing belt pieces with items did not throw' + (threw ? ': ' + threw.message : '')); S.floor.length = fl0; S.custom = (S.custom || []).filter((c) => cid0.indexOf(c.id) >= 0); if (T.edit.on) T.editToggle(); }
  T.setTime(19); const day0 = S.day; T.sleepNow(); ok(S.day === day0 + 1 && S.time === 6, 'slept to day ' + S.day);
  T.save(); const raw = JSON.parse(localStorage.getItem('depotco-slot1')); ok(raw && raw.day === S.day && raw.up.fork === true, 'save written');
  // the boot-time parcel check knows every place a parcel can be: a belt, the cart, the pack line outlet (missing these reopened packed orders and refilled the bench at every launch)
  { const po = T.genOrder(false) || (S.slots[T.slotKey(2, 9, 0)] = { sku: 'cereal', n: 12, pal: true }, T.genOrder(false)); if (po) {   /* the deck accounts can claim every free box; top the racks up */ po.state = 'packed'; T.beltItems('shipBelt').push({ kind: 'parcel', order: po.id, d: 1 }); ok(T.parcelExists(po.id), 'a parcel riding the shipping belt counts as existing'); T.beltItems('shipBelt').pop(); S.cart.parcels = S.cart.parcels || []; S.cart.parcels.push(po.id); ok(T.parcelExists(po.id), 'a parcel on the cart counts'); S.cart.parcels.pop(); S.pack.out = po.id; ok(T.parcelExists(po.id), 'a parcel waiting at the pack line outlet counts'); S.pack.out = null; ok(!T.parcelExists(po.id), 'and a parcel that is nowhere is nowhere'); S.orders.splice(S.orders.indexOf(po), 1); } else ok(false, 'could not generate an order for the parcel check'); }
  // hall 5 (1.13.3): a hall-4 save with six rows and stock in the old row A comes back with five rows, the stock moved into free slots, crane states and moved racks shifted down, the sixth row refunded
  { const keep = localStorage.getItem('depotco-slot1'); const old = JSON.parse(keep); old.hall = 4; old.up.rows = 6; old.bank = 1000; old.doors = [false, false, false, false]; (old.orders || []).forEach((o) => { delete o.mode; }); old.slots = { '0,3,0': { sku: 'paint', n: 5, pal: true }, '5,2,1': { sku: 'bolts', n: 2, pal: true }, '0,3,1': { sku: 'soap', n: 1, pal: true } }; old.gantries = { 0: { state: 'toBay', sku: 'paint', key: '0,3,0' }, 5: { state: 'idle' } }; old.layout = { rack2: { x: 0, z: 2.3, rot: 0 }, gantry0: { x: 1 } }; localStorage.setItem('depotco-slot1', JSON.stringify(old));
    const okLoad = T.load(); const M = T.state(); const keys = Object.keys(M.slots).filter((k) => M.slots[k] && M.slots[k].n > 0);
    ok(okLoad && M.hall === 5 && M.up.rows === 5 && M.bank > 1000, 'a hall-4 save migrates to five rows with the sixth refunded: hall=' + M.hall + ' rows=' + M.up.rows + ' bank=' + M.bank);
    ok(M.slots['4,2,1'] && M.slots['4,2,1'].sku === 'bolts' && !M.slots['5,2,1'], 'row F stock is now row E stock');
    const paintK = keys.filter((k) => M.slots[k].sku === 'paint')[0], soapK = keys.filter((k) => M.slots[k].sku === 'soap')[0];
    ok(!!paintK && !!soapK && +paintK.split(',')[0] < 5 && keys.length === 3 && !M.pallets.some((p) => /^pl-mig/.test(p.id)), 'old row A stock moved into free slots of the rows kept: ' + keys.join(' '));
    ok(Object.keys(M.gantries).join(',') === '4' && M.gantries[4].state === 'idle', 'crane states shifted down a row: ' + Object.keys(M.gantries).join(','));
    ok(!!M.layout.rack1 && !M.layout.rack2 && !M.layout.gantry0, 'moved racks shift down a row');
    ok(M.doors.length === 7 && M.orders.every((o) => !!o.mode), 'seven dock doors and a lane on every order after the load');
    localStorage.setItem('depotco-slot1', keep); T.load(); }
  // 1.18.0: a worker can be looked at; the crew's jacks park in a row by the west wall at clock-out; off duty means home; the returns dock has a console
  { const SL = T.S, rcv = SL.staff.filter((st) => st.role === 'receiver')[0], pk = SL.staff.filter((st) => st.role === 'picker')[0];   // after the load test S is the old object: read the live one
    ok(!!T.propInst.consoleRet && Math.abs(T.propWorld('consoleRet', 0, 0).x - (T.HALL.x - 0.3)) < 0.01 && !T.collides(T.HALL.x - 1.4, T.RET.dockZ + 3.4), 'the returns dock has its console on the east wall');
    if (rcv) { const m = T.staffMeshes[rcv.id]; ok(!!m && !!m.userData.hit && m.userData.hit.userData.it && m.userData.hit.userData.it.staffId === rcv.id && /reliable|timekeeper/.test(T.staffPrompt(rcv)), 'a worker has a hit box and a prompt with their timekeeping: ' + T.staffPrompt(rcv));
      const jh = T.jackHome(rcv); ok(Math.abs(jh.x - (-T.HALL.x + 1.3)) < 0.01 && jh.z >= 11.3 && !T.collides(jh.x, jh.z) && T.insideHall(jh.x, jh.z), 'the receiver jack slot is by the west wall and clear: ' + jh.x.toFixed(1) + ',' + jh.z.toFixed(1));
      const t0 = SL.time, d0 = rcv.dayOff; rcv.state = 'idle'; rcv.task = null; rcv.carry = null; rcv.clocked = true; rcv.clockedOutAt = null; rcv.jackParked = false; rcv.x = -20; rcv.z = 0; rcv.jackAt = { x: -21.5, z: 0, ry: 0 }; rcv.shift = 'day'; rcv.overtime = false; rcv.dayOff = false; rcv.sick = false; T.setTime(18.1); T.run(2);
      ok(rcv.state === 'walk' && rcv.then === 'parkJack', 'at the end of the shift a receiver walks the jack to its slot first: ' + rcv.state + '/' + rcv.then);
      T.run(45); ok(!!rcv.jackParked && !!rcv.jackAt && Math.abs(rcv.jackAt.x - jh.x) < 0.01 && Math.abs(rcv.jackAt.z - jh.z) < 0.01 && rcv.clocked === false, 'the jack stands in its slot and the receiver clocked out: ' + rcv.state + ' parked=' + rcv.jackParked + ' at ' + (rcv.jackAt ? rcv.jackAt.x.toFixed(1) + ',' + rcv.jackAt.z.toFixed(1) : '-'));
      rcv.dayOff = d0; T.setTime(t0); }
    if (pk) { const t1 = SL.time; pk.state = 'idle'; pk.task = null; pk.carry = null; pk.clocked = false; pk.clockedOutAt = null; pk.x = -10; pk.z = 5; pk.dayOff = true; T.setTime(10); T.run(1); ok(pk.state === 'home' || pk.state === 'gone' || (pk.state === 'walk' && pk.then === 'gone'), 'an off-duty worker standing in the hall walks out: ' + pk.state + '/' + pk.then); pk.dayOff = false; T.setTime(t1); } }
  // 1.18.1: the rooms' furniture stands, the shop sells more, and comfort shortens the breaks
  { const fset = ['tv', 'dartboard', 'microwave', 'fanStand', 'rugLobby', 'rugOffice', 'bookshelf', 'printer', 'pictureOffice', 'pictureLobby'], missing = fset.filter((id) => !T.propInst[id]);
    ok(!missing.length, 'the rooms have their furniture: ' + (missing.length ? 'missing ' + missing.join(', ') : fset.length + ' pieces'));
    const mw = T.propWorld('microwave', 0, 0), bs = T.propWorld('bookshelf', 0, 0); ok(mw.x < -35 && mw.z < -22 && mw.z > -23 && bs.x > 30 && bs.z > 23, 'the microwave sits on the coffee counter and the bookshelf against the office wall');
    ok(!T.collides(-31.4, -20.75) && !T.collides(31.2, 22.9) && !T.collides(-33.6, 21.6), 'the break room floor under the dartboard, the office floor by the bookshelf and the lobby rug are walkable');
    const cf0 = T.roomComfort(); ok(cf0 >= 4 && cf0 <= 10 && T.breakLen() < 0.5 && T.breakLen() >= 0.25, 'the furniture gives comfort ' + cf0 + ' and a break of ' + Math.round(T.breakLen() * 60) + ' min');
    ok(['xSofa', 'xArmchair', 'xPaddedChair', 'xRoundTable', 'xTv', 'xDartboard', 'xMicrowave', 'xFan', 'xRug', 'xBookshelf', 'xPrinter', 'xPicture'].every((id) => T.PROPS[id] && T.PROPS[id].extra && T.PROPS[id].price > 0), 'twelve pieces of furniture are in the shop'); }
  // 1.19.0: the scanner acts: Enter on a Docks row toggles the door, on a truck row signs or dispatches, on the crew page punches your clock
  { const SL = T.S; SL.events.power = false; T.scanToggle(true); T.scanPage(5); T.drawScanner(); let rows = T.scanDev.rows;
    const di = rows.findIndex((r) => r.act && /^(OPEN|CLOSE)$/.test(r.act.label)); ok(di >= 0, 'the Docks page offers OPEN or CLOSE on a door row: ' + (di >= 0 ? rows[di].text : 'none'));
    if (di >= 0) { const label0 = rows[di].act.label, open0 = /IN 1/.test(rows[di].text) ? SL.doors[0] : null; T.scan.sel = di; const did = T.scanAct(); T.drawScanner(); rows = T.scanDev.rows; ok(did && rows[di].act.label !== label0, 'Enter toggled the door: ' + label0 + ' then ' + rows[di].act.label); T.scan.sel = di; T.scanAct(); T.drawScanner(); ok(T.scanDev.rows[di].act.label === label0, 'and back again'); }
    rows = T.scanDev.rows; const tr = rows.findIndex((r) => r.act && /^(SIGN|DISPATCH)$/.test(r.act.label)); if (tr >= 0) ok(/truck/.test(rows[tr].text), 'a docked truck has its own row with ' + rows[tr].act.label + ': ' + rows[tr].text.trim());
    T.scanPage(7); T.drawScanner(); rows = T.scanDev.rows; const yi = rows.findIndex((r) => /^You/.test(r.text)); ok(yi >= 0 && rows[yi].act && /CLOCK/.test(rows[yi].act.label), 'the crew page offers your clock: ' + (yi >= 0 && rows[yi].act ? rows[yi].act.label : 'none'));
    if (yi >= 0) { const c0 = SL.clockedIn; T.scan.sel = yi; T.scanAct(); ok(SL.clockedIn !== c0, 'Enter punched the clock: ' + (SL.clockedIn ? 'in' : 'out')); T.drawScanner(); T.scan.sel = yi; T.scanAct(); ok(SL.clockedIn === c0, 'and punched it back'); }
    T.scanPage(1); T.drawScanner(); rows = T.scanDev.rows; ok(rows.every((r) => !r.act || /^PACK$/.test(r.act.label) || /RETURN/.test(r.act.label)), 'the Orders page offers PACK on orders and nothing odd elsewhere');
    T.scanPage(6); T.drawScanner(); rows = T.scanDev.rows; ok(rows.some((r) => r.act), 'the Plant page carries the machine buttons: ' + rows.filter((r) => r.act).length + ' rows act');
    T.scan.sel = 0; T.scanPage(0); T.drawScanner(); T.scan.sel = 0; ok(T.scanAct() === false, 'Enter on a row with nothing to do says so instead of throwing'); T.scanToggle(false); }
  // 1.19.1: the scanner's view follows the cursor down a long page (Stock, Orders): the line that did it sat inside a comment since 1.16
  { T.scanToggle(true); T.scanPage(6); T.scan.sel = 0; T.drawScanner(); const n = T.scanDev.rows.length; ok(n > 8, 'the Plant page is long enough to scroll: ' + n + ' rows'); for (let i = 0; i < n + 2; i++) T.scanScroll(1); ok(T.scan.sel === n - 1 && T.scan.scroll === Math.max(0, n - 8), 'the Plant page scrolls to its last row: sel ' + T.scan.sel + ' of ' + n + ', scroll ' + T.scan.scroll); for (let i = 0; i < n + 2; i++) T.scanScroll(-1); ok(T.scan.sel === 0 && T.scan.scroll === 0, 'and back to the top'); T.scanToggle(false); }
  const c = T.counts(); out.push('info draws=' + c.draws + ' inter=' + c.inter + ' dyn=' + c.dyn);
  } catch (e) { errs.push('scenario threw: ' + (e && e.stack || e)); }   // the checks that passed before the throw still print, and the stack says where
  return { out, errs };
})()`;

app.whenReady().then(async () => {
  const win = new BrowserWindow({ show: false, width: 1280, height: 720, webPreferences: { contextIsolation: true, nodeIntegration: false, sandbox: true, offscreen: true } });
  const pageErrors = [];
  win.webContents.on('console-message', (e, level, msg, line, src) => { if (level >= 2 && !/Electron Security Warning/.test(msg)) pageErrors.push(msg + ' @ ' + String(src).split('/').pop() + ':' + line); });
  win.webContents.on('render-process-gone', (e, d) => { pageErrors.push('renderer gone: ' + d.reason); });
  await win.loadFile(path.join(__dirname, '..', 'game', 'index.html'));
  await new Promise((r) => setTimeout(r, 1500));
  let result;
  try { result = await Promise.race([win.webContents.executeJavaScript(SCENARIO, true), new Promise((_, rej) => setTimeout(() => rej(new Error('timeout')), 180000))]); }
  catch (e) { result = { out: [], errs: ['scenario threw: ' + (e && e.message || e)] }; }
  result.out.forEach((l) => console.log('  ' + l));
  result.errs.filter((e) => /^scenario threw/.test(e)).forEach((l) => console.log('  ' + l));
  pageErrors.forEach((l) => console.log('  PAGE ' + l));
  const failed = result.errs.length + pageErrors.length;
  console.log(failed ? 'smoke: FAILED (' + failed + ')' : 'smoke: all ' + result.out.filter((l) => /^ok/.test(l)).length + ' checks passed');
  app.exit(failed ? 1 : 0);
});
