// Writes game/version.js from package.json so the game and the main menu state the same version.
var fs = require('fs'), path = require('path'); var v = require('../package.json').version;
var out = path.join(__dirname, '..', 'game', 'version.js');
var text = '// generated by tools/sync-version.js from package.json; do not edit\nwindow.DEPOT_VERSION = ' + JSON.stringify(v) + ';\n';
if (!fs.existsSync(out) || fs.readFileSync(out, 'utf8') !== text) fs.writeFileSync(out, text);
console.log('game/version.js: ' + v);
